---
title: "zoops_mb_analysis"
output: html_document
date: "2023-02-13"
---
```{r loading packages}

library("tidyverse")
library("ggplot2")
library("phyloseq")
library("vegan")
library("cowplot")
library("gridExtra")
library("ggpubr")
library("dplyr")
library("doBy")
library(RColorBrewer)
library(glue)
library(ecodist)
library(geosphere)
library(data.table)
library("patchwork")
library("ggpubr")
library("car")
library(ggcorrplot)
library("FactoMineR")
library("devtools")
library("factoextra")

# use pacman to load CRAN packages missing
pacman::p_load('knitr', 'tidyverse', 'knitr', 'magrittr', 'effects', 'devtools',
               'stringi', 'dplyr', "ggplot2", "gridExtra", "dada2", "phyloseq", "vegan",
               "cowplot", "decontam","BiocManager", "dada2", "microbiome", "BiocManager")

install.packages("ggcorrplot")


install.packages("FactoMineR")


library("devtools")
install_github("kassambara/factoextra")
library("factoextra")


remotes::install_github("microbiome/microbiome")
library("microbiome")

devtools::install_github("microbiome/mia")
library("mia")

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("DESeq2")
```


```{r loading in data and modifying metadata}

# load in CSV files for phyloseq object
metadata <- read.csv('phyloseq analysis/metadata_mp.csv')
ASV_table <- read.csv('phyloseq analysis/otu_table.csv')
tax_table <- read.csv('phyloseq analysis/tax_table.csv')  


# modify metadata
str(metadata)
table(metadata$organism)

# set row names
row.names(metadata) <- metadata$X

metadata$date <- as.Date(metadata$date)

# factors
metadata$sample_ID <- as.factor(metadata$sample_ID)
metadata$sequencing_ID <- as.factor(metadata$sequencing_ID)
metadata$sample_type <- as.factor(metadata$sample_type)
metadata$organism_water <- as.factor(metadata$organism_water)
metadata$time_point <- as.factor(metadata$time_point)
metadata$date <- as.factor(metadata$date)
metadata$lake <- as.factor(metadata$lake)

# numerics
metadata$number <- as.numeric(metadata$number)
metadata$latitude <- as.numeric(metadata$latitude)
metadata$longitude <- as.numeric(metadata$longitude)
metadata$elevation_m <- as.numeric(metadata$elevation_m)
metadata$temp_C <- as.numeric(metadata$temp_C)
metadata$chla_ug.L <- as.numeric(metadata$chla_ug.L)
metadata$pH <- as.numeric(metadata$pH)
metadata$DO_perc <- as.numeric(metadata$DO_perc)
metadata$spc <- as.numeric(metadata$spc)
metadata$cond <- as.numeric(metadata$cond)
metadata$DOC <- as.numeric(metadata$DOC)
metadata$TDN <- as.numeric(metadata$TDN)
metadata$TDP <- as.numeric(metadata$TDP)

#check
class(metadata$sample_ID)
class(metadata$elevation_m)
class(metadata$spc)
str(metadata)


# make new column for cladocerans, copepoda, water
metadata$phy_group <- ifelse(metadata$organism == "Calanoid" | metadata$organism == "Cyclopoid" | metadata$organism =="Large Calanoid", "copepoda", ifelse(metadata$organism == "Water", "water", "cladocera"))

#make new column for elevation category
metadata$elev.cat <- as.factor(ifelse(metadata$elevation_m < 2900, "Below", "Above"))

# make a new column for basin category
metadata$basin <- as.factor(ifelse(metadata$lake == "Eastern Brook" | metadata$lake == "Serene", "South", ifelse(metadata$lake == "Cooney" | metadata$lake == "Blue" | metadata$lake == "Virginia", "North", "Middle")))



#check that the new column called phy_group worked
levels(as.factor(metadata$phy_group))
levels(as.factor(metadata$elev.cat))

metadata$phy_group <- as.factor(metadata$phy_group)


```


```{r making phyloseq objects}

PS.fin<-
  read_phyloseq(
    otu.file = "phyloseq analysis/otu_table.csv",
    taxonomy.file = "phyloseq analysis/tax_table.csv",
    metadata.file = "phyloseq analysis/metadata_mp.csv",
    type = c("simple"),
    sep = ","
  ) 
str(PS.fin)

nsamples(PS.fin)
ntaxa(PS.fin)
head(taxa_sums(PS.fin))


PS.fin <- subset_taxa(PS.fin, Family!= "Mitochondria" | 
                                is.na(Family) & Class!="Chloroplast" | is.na(Class))

PS.zoops <- subset_samples(PS.fin, sample_type == "Zooplankton")
sample_data(PS.zoops)$phy_group <- ifelse(sample_data(PS.zoops)$organism_water == "Calanoid" | sample_data(PS.zoops)$organism_water == "Cyclopoid" | sample_data(PS.zoops)$organism_water =="Large Calanoid", "copepoda", "cladocera")
PS.water <- subset_samples(PS.fin, sample_type == "Water")

# change sample names to match 
sample_names(PS.fin) <- metadata$sequence_ID
rownames(metadata) <- metadata$sequence_ID
sample_data(PS.fin) <- metadata


########### let's inspect
df.fin <- as.data.frame(sample_data(PS.fin))
df.fin$LibrarySize <- sample_sums(PS.fin) # this is the # of reads
df.fin$Index <- seq(nrow(df.fin))

########### now we have final phyloseq object with correct metadata 
saveRDS(PS.fin, file="phyloseq analysis/output/PS.fin.rds")
PS.fin <- readRDS("phyloseq analysis/output/PS.fin.rds")


# Make a data frame with a column for the read counts of each sample
sample_data(PS.fin)$read_depth <- sample_sums(PS.fin)
sample_sum_df <- data.frame(read.sum = sample_sums(PS.fin))
View(sample_sum_df)
median(sample_sum_df$read.sum)


# make row names the sample names
colnames(sample_sum_df) <- "read.sum"
sample_sum_df$sequence_ID <- rownames(sample_sum_df)

# merge in the reads
run.metaD <- merge(metadata, sample_sum_df, by="sequence_ID", all.y=TRUE)
write.csv(run.metaD, "phyloseq analysis/output/run.metaD.final.csv")
```


```{r taxa compositions}


library(plyr)
# finding average abundance of each class of bacteria for zoops overall
glom <- tax_glom(PS.zoops, taxrank = 'Class')
CGroup <- transform_sample_counts(glom, function(x)100* x / sum(x))
OTUg <- otu_table(CGroup)
TAXg <- tax_table(CGroup)[,"Class"]
AverageD <- as.data.frame(rowMeans(OTUg))
names(AverageD) <- c("Mean")
GTable <- merge(TAXg, AverageD, by=0, all=TRUE)
GTable$Row.names = NULL
GTable <- GTable[order(desc(GTable$Mean)),]
head(GTable, 18)




```



```{r total reads by species boxplots}

# Box plots showing spread of total reads by species

box1 <- ggplot(sample_data(PS.fin), aes(x=organism_water, y=read_depth)) + geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90)) + labs(y= "Read Depth", x = "Organism")
box1
dev.copy(pdf, "phyloseq analysis/figures/reads.sample.pdf", height=4, width=7)
dev.off() 

box2 <- ggplot(sample_data(PS.fin), aes(x=organism_water, y=log(read_depth))) + geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90)) + labs(y= "log(Read Depth)", x = "Organism")
box2
dev.copy(pdf, "phyloseq analysis/figures/reads.sample.pdf", height=4, width=7)
dev.off() 

```


```{r Read counts and rarefaction curves}

readcount = data.table(as(sample_data(PS.fin), "data.frame"),
                       TotalReads = sample_sums(PS.fin),
                       keep.rownames = T)
ggplot(readcount, aes(TotalReads)) + geom_histogram() + ggtitle("Sequencing Depth")

view(readcount[order(readcount$TotalReads)])

# Histogram of sample read counts
hist.depth <- ggplot(sample_sum_df, aes(x = read.sum)) + 
  geom_histogram(color = "black", fill = "gold2", binwidth = 2500) +
  ggtitle("Distribution of sample sequencing depth") + 
  xlab("Read counts") +
  theme(axis.title.y = element_blank()) + theme_classic() + geom_vline(xintercept=1000, lty=2)
hist.depth
dev.copy(pdf, "phyloseq analysis/figures/hist.depth.pdf", height=4, width=5)
dev.off() 


# zoom in a bit on the mode of the histogram
zoom.hist.depth<-ggplot(sample_sum_df, aes(x = read.sum)) + 
  geom_histogram(color = "black", fill = "gold2", binwidth = 1000) + coord_cartesian(xlim=c(0, 5000)) +
  ggtitle("Distribution of sample sequencing depth") + 
  xlab("Read counts") +
  theme(axis.title.y = element_blank()) + theme_classic() + geom_vline(xintercept=1000, lty=2)
zoom.hist.depth
dev.copy(pdf, "phyloseq analysis/figures/zoom.hist.depth.pdf", height=4, width=5)
dev.off() 

# a different view
read_depth_violin <- ggplot(sample_sum_df, aes(x=1, y=read.sum)) +
  geom_violin() + ggtitle("Distribution of sample sequencing depth") + scale_y_log10() +
  xlab("Samples") + ylab("Read Depth")
read_depth_violin
dev.copy(pdf, "phyloseq analysis/figures/read_depth_violin.pdf", height=4, width=5)
dev.off()

read_depth_violin <- read_depth_violin + geom_boxplot(width=0.1)
read_depth_violin
dev.copy(pdf, "phyloseq analysis/figures/read_depth_violin.pdf", height=4, width=5)
dev.off()

# Rarefaction curve
count_table_filt <- as.data.frame(otu_table(PS.fin))
rarecurve((count_table_filt), step=50, cex=0.5, xlim=c(0,100000), ylab = "ASVs", label=FALSE)
abline(v = 5000, lty = "dotted", col="red", lwd=2)

dev.copy(pdf, "phyloseq analysis/figures/rare.raw.pdf", height=4, width=5)
dev.off() 
```


```{r exploring what low read count samples do and what to rarefy to}

ord <- ordinate(PS.fin, method = 'PCoA', distance = 'bray')
plot_ordination(PS.fin, ord, color = "sample_type")
sample_data(PS.fin)$read_depth <- sample_sums(PS.fin)
plot_ordination(PS.fin, ord, shape = "sample_type") +
  geom_point(aes(color = read_depth > 500))


ord <- ordinate(PS.rare, method = 'PCoA', distance = 'bray')
plot_ordination(PS.rare, ord, shape = "sample_type") +
  geom_point(aes(color = read_depth))
sample_data(PS.rare)$read_depth <- sample_sums(PS.rare)


ord <- ordinate(PS.rare, method = 'PCoA', distance = 'bray')
plot_ordination(PS.rare, ord, color = "time_point") +
  geom_point() +
  stat_ellipse(level=0.9, linetype = 2)


```



```{r rarefy}


table(sample_data(PS.fin)$sample_type)

# rarefying to 500 reads (both the zoops and water)
set.seed(10000)
PS.500 <- rarefy_even_depth(PS.fin, rngseed=1e4, sample.size = 500)
sort(rowSums(otu_table(t(PS.500))))

# filtering metadata by sample names with 500 reads or more, 49 samples lost
metadata_500 <- as.data.frame(sample_data(PS.500))
metadata_500$sequence_ID <- rownames(PS.500) 
table(sample_data(PS.500)$sample_type)



# rarefying to 500 reads for just zoops
set.seed(10000)
PS.zoops <- rarefy_even_depth(PS.zoops, rngseed=1e4, sample.size = 500)
table(sample_data(PS.zoops)$phy_group, sample_data(PS.zoops)$time_point, sample_data(PS.zoops)$lake)


```


```{r exploratory alpha diversity plots}

library(multcompView)

#richness by Lake for zoops only
richness.plot.location <- plot_richness(PS.zoops, x="lake", measures=c("Observed", "Shannon")) + 
  labs(y= "Alpha Diversity Measure", x = "Lake") + theme_bw() + geom_boxplot() + 
  theme(axis.text.x = element_text(angle = 90)) + stat_compare_means(method = "anova") +
  theme(axis.text.x=element_text(size=9)) + theme(strip.text.x = element_text(size = 12)) +
  ggtitle("Zooplankton Samples- Microbial Community Alpha Diversity")
richness.plot.location
dev.copy(pdf, "phyloseq analysis/figures/richness.plot.location.pdf", height=5, width=7)
dev.off()

# I need to group the treatments that are not different each other together.
generate_label_df <- function(tukey.test, lake){
 
     # Extract labels and factor levels from Tukey post-hoc 
     Tukey.levels <- tukey.test[["lake"]][,4]
     Tukey.labels <- data.frame(multcompLetters(Tukey.levels)['Letters'])
     
     #I need to put the labels in the same order as in the boxplot :
     Tukey.labels$lake=rownames(Tukey.labels)
     Tukey.labels=Tukey.labels[order(Tukey.labels$lake) , ]
     return(Tukey.labels)
     }
 
# Apply the function on my dataset
LABELS <- generate_label_df(tukey.test, "data$treatment")

 
# Draw the basic boxplot
a <- boxplot(data$value ~ data$treatment, ylim=c(min(data$value), 1.1*max(data$value)), ylab="value" , main="")
 
# I want to write the letter over each box. Over is how high I want to write it.
over <- 0.1*max( a$stats[nrow(a$stats),] )
 
#Add the labels
text( c(1:nlevels(data$treatment)) , a$stats[nrow(a$stats),]+over , LABELS[,1]  , col=my_colors[as.numeric(LABELS[,1])] )

#richness by Lake for water only
water.richness.plot.location <- plot_richness(PS.water, x="lake", measures=c("Observed", "Shannon")) + 
  labs(y= "Alpha Diversity Measure", x = "Lake") + theme_bw() + geom_boxplot() + 
  theme(axis.text.x = element_text(angle = 90)) + stat_compare_means(method = "anova") +
  theme(axis.text.x=element_text(size=9)) + theme(strip.text.x = element_text(size = 12)) + 
  ggtitle("Water Samples- Microbial Community Alpha Diversity")
water.richness.plot.location
dev.copy(pdf, "phyloseq analysis/figures/water.richness.plot.location.pdf", height=5, width=7)
dev.off()


#richness by organism (or sample type i.e, water)
richness.plot.organism <- plot_richness(PS.500, x="sample_type", measures=c("Observed", "Shannon")) + 
  labs(y= "Alpha Diversity Measure", x = "Organism") + theme_bw() + geom_boxplot() + 
  theme(axis.text.x = element_text(angle = 90)) + stat_compare_means(method = "anova")
richness.plot.organism
dev.copy(pdf, "phyloseq analysis/figures/richness.plot.organism.pdf", height=4, width=12)
dev.off() 


#richness by phy_group (or sample type i.e, water)
richness.plot.phy <- plot_richness(PS.rare, x="phy_group", measures=c("Observed", "Shannon")) +
  labs(y= "Alpha Diversity Measure", x = "Sample Type") + theme_bw() + geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90)) + stat_compare_means(method = "anova")
richness.plot.phy
dev.copy(pdf, "phyloseq analysis/figures/richness.plot.phy.pdf", height=4, width=12)
dev.off() 


#richness by Time.point
richness.plot.time.point <- plot_richness(PS.zoops, x="time_point", measures=c("Observed", "Shannon")) + 
  labs(y= "Alpha Diversity Measure", x = "Time Point") + theme_bw() + geom_boxplot() +
  stat_compare_means(method = "anova")
richness.plot.time.point
dev.copy(pdf, "phyloseq analysis/figures/richness.plot.time.point.pdf", height=4, width=10)
dev.off() 


richness.plot.time.point500 <- plot_richness(PS.500, x="time_point", measures=c("Observed", "Shannon")) + 
  labs(y= "Alpha Diversity Measure", x = "Time Point") + theme_bw() + geom_boxplot() +
  stat_compare_means(method = "anova")
richness.plot.time.point500
dev.copy(pdf, "phyloseq analysis/figures/richness.plot.time.point500.pdf", height=4, width=10)
dev.off() 


richness.plot.time.point1000 <- plot_richness(PS.1000, x="time_point", measures=c("Observed", "Shannon")) + 
  labs(y= "Alpha Diversity Measure", x = "Time Point") + theme_bw() + geom_boxplot() +
  stat_compare_means(method = "anova")

richness.plot.time.point1000
dev.copy(pdf, "phyloseq analysis/figures/richness.plot.time.point1000.pdf", height=4, width=10)
dev.off() 


```



```{r ASV Richness and Diversity Plots}


library(lattice)
library(Hmisc)
library(ggplot2)
library(sciplot)
library(reshape)
library(doBy)
library(car)
library(readr)


rich.rare <- richness(otu_table(PS.500), index="observed")
div.rare <- diversity(otu_table(PS.500), index="shannon")

rare.a.diversity <- cbind(rich.rare, div.rare)
rare.a.diversity$sequencing_ID <- rownames(div.rare)


rare.a.diversity <- cbind(rare.a.diversity, sample_data(PS.500)[,c(3,4,7,8,9,22)])

rare.sum_div <- summaryBy(shannon ~ lake*time_point, data = rare.a.diversity, FUN = c(mean, sd))
#sum_div.sample_type <- summaryBy(shannon ~ sample_type, data = rare.a.diversity, FUN = c(mean, sd))
rare.sum_rich <- summaryBy(observed ~ lake*time_point, data = rare.a.diversity, FUN = c(mean, sd))

rare_div_lm <- lm(shannon ~ lake*time_point, data = rare.a.diversity)
rare_anova_div <- aov(rare_div_lm)
summary(rare_anova_div)
rare.tukey.test <- TukeyHSD(anova_div, conf.level=0.95)


rare_rich_lm <- lm(observed ~ lake*time_point, data = rare.a.diversity)
rare_anova_rich <- Anova(rare_rich_lm)
summary(rare_anova_rich)

rare.a.div.thru.time <- ggplot(rare.sum_div, aes(x=time_point, y=shannon.mean, group=lake))+
  facet_grid(rows="lake") +
  ylim(1,5) +
  geom_point(size = 1.2) +
  geom_line(size = 0.3) +
  xlab('Sampling Time Point') +
  ylab('Average Shannon Diversity') +
  geom_errorbar(aes(ymin=shannon.mean - shannon.sd, ymax=shannon.mean + shannon.sd), width=.05,
                 position=position_dodge(0.05)) +
  theme(strip.text.y = element_text(size = 8, hjust = 0.5,
          vjust = 0.5, face = 'bold'))
rare.a.div.thru.time
dev.copy(pdf, "phyloseq analysis/figures/rare.a.div.thru.time.pdf", height=6, width=8)
dev.off() 

rare.rich.thru.time <- ggplot(sum_rich, aes(x=time_point, y=observed.mean, group=lake))+
  facet_grid(rows="lake") +
  ylim(10,150) +
  geom_point(size = 1.2) +
  geom_line(size = 0.3) +
  xlab('Sampling Time Point') +
  ylab('Average Richness') +
  geom_errorbar(aes(ymin=observed.mean - observed.sd, ymax=observed.mean + observed.sd), width=.05,
                 position=position_dodge(0.05)) +
theme(strip.text.y = element_text(size = 8, hjust = 0.5,
          vjust = 0.5, face = 'bold')) +
  stat_compare_means(method = "anova")
rare.rich.thru.time
dev.copy(pdf, "phyloseq analysis/figures/rare.rich.thru.time.pdf", height=6, width=8)
dev.off() 

#####


rich <- richness(otu_table(PS.zoops), index="observed")
div <- diversity(otu_table(PS.zoops), index="shannon")

a.diversity <- cbind(rich, div)
a.diversity$sequencing_ID <- rownames(div)


a.diversity <- cbind(a.diversity, sample_data(PS.zoops)[,c(7,8,9,22)])

sum_div <- summaryBy(shannon ~ lake*time_point, data = a.diversity, FUN = c(mean, sd))
sum_div.lake <- summaryBy(shannon ~ lake, data = a.diversity, FUN = c(mean, sd))
sum_rich <- summaryBy(observed ~ lake*time_point, data = a.diversity, FUN = c(mean, sd))

div_lm <- lm(shannon ~ lake*time_point, data = a.diversity)
anova_div <- aov(div_lm)
tukey.test <- TukeyHSD(anova_div, conf.level=0.95)


rich_lm <- lm(observed ~ lake*time_point, data = a.diversity)
anova_rich <- Anova(rich_lm)


a.div.thru.time <- ggplot(sum_div, aes(x=time_point, y=shannon.mean, group=lake))+
  facet_grid(rows="lake") +
  ylim(1,5) +
  geom_point(size = 1.2) +
  geom_line(size = 0.3) +
  xlab('Sampling Time Point') +
  ylab('Average Shannon Diversity') +
  geom_errorbar(aes(ymin=shannon.mean - shannon.sd, ymax=shannon.mean + shannon.sd), width=.05,
                 position=position_dodge(0.05)) +
  theme(strip.text.y = element_text(size = 8, hjust = 0.5,
          vjust = 0.5, face = 'bold'))
a.div.thru.time
dev.copy(pdf, "phyloseq analysis/figures/a.div.thru.time.pdf", height=6, width=8)
dev.off() 

rich.thru.time <- ggplot(sum_rich, aes(x=time_point, y=observed.mean, group=lake))+
  facet_grid(rows="lake") +
  ylim(10,150) +
  geom_point(size = 1.2) +
  geom_line(size = 0.3) +
  xlab('Sampling Time Point') +
  ylab('Average Richness') +
  geom_errorbar(aes(ymin=observed.mean - observed.sd, ymax=observed.mean + observed.sd), width=.05,
                 position=position_dodge(0.05)) +
theme(strip.text.y = element_text(size = 8, hjust = 0.5,
          vjust = 0.5, face = 'bold')) +
  stat_compare_means(method = "anova")
rich.thru.time
dev.copy(pdf, "phyloseq analysis/figures/rich.thru.time.pdf", height=6, width=8)
dev.off() 

#####

clad_sum_div <- summaryBy(shannon ~ lake*time_point*phy_group, data = a.diversity[a.diversity$phy_group == "cladocera", ], FUN = c(mean, sd))
clad_sum_rich <- summaryBy(observed ~ lake*time_point*phy_group, data = a.diversity[a.diversity$phy_group == "cladocera", ], FUN = c(mean, sd))


clad_div_lm <- lm(shannon ~ lake*time_point, a.diversity[a.diversity$phy_group == "cladocera", ])
Anova(clad_div_lm)

clad_rich_lm <- lm(observed ~ lake*time_point, data = a.diversity[a.diversity$phy_group == "cladocera", ])
Anova(clad_rich_lm)


Clad.a.div.thru.time <- ggplot(clad_sum_div, aes(x=time_point, y=shannon.mean, group=lake))+
  facet_grid(rows="lake") +
  ylim(1,5) +
  geom_point(size = 1.2) +
  geom_line(size = 0.3) +
  xlab('Sampling Time Point') +
  ylab('Average Shannon Diversity') +
  geom_errorbar(aes(ymin=shannon.mean - shannon.sd, ymax=shannon.mean + shannon.sd), width=.05,
                 position=position_dodge(0.05)) +
  theme(strip.text.y = element_text(size = 8, hjust = 0.5,
          vjust = 0.5, face = 'bold')) +
  ggtitle("Cladocera")
Clad.a.div.thru.time
dev.copy(pdf, "phyloseq analysis/figures/Clad.a.div.thru.time.pdf", height=6, width=8)
dev.off() 

Clad.rich.thru.time <- ggplot(clad_sum_rich, aes(x=time_point, y=observed.mean, group=lake))+
  facet_grid(rows="lake") +
  ylim(10,150) +
  geom_point(size = 1.2) +
  geom_line(size = 0.3) +
  xlab('Sampling Time Point') +
  ylab('Average Richness') +
  geom_errorbar(aes(ymin=observed.mean - observed.sd, ymax=observed.mean + observed.sd), width=.05,
                 position=position_dodge(0.05)) +
theme(strip.text.y = element_text(size = 8, hjust = 0.5,
          vjust = 0.5, face = 'bold')) +
  ggtitle("Cladocera")
Clad.rich.thru.time
dev.copy(pdf, "phyloseq analysis/figures/Clad.rich.thru.time.pdf", height=6, width=8)
dev.off() 

###

cop_sum_div <- summaryBy(shannon ~ lake*time_point*phy_group, data = a.diversity[a.diversity$phy_group == "copepoda", ], FUN = c(mean, sd))
cop_sum_rich <- summaryBy(observed ~ lake*time_point*phy_group, data = a.diversity[a.diversity$phy_group == "copepoda", ], FUN = c(mean, sd))

Cop.a.div.thru.time <- ggplot(cop_sum_div, aes(x=time_point, y=shannon.mean, group=lake))+
  facet_grid(rows="lake") +
  ylim(1,5) +
  geom_point(size = 1.2) +
  geom_line(size = 0.3) +
  xlab('Sampling Time Point') +
  ylab('Average Shannon Diversity') +
  geom_errorbar(aes(ymin=shannon.mean - shannon.sd, ymax=shannon.mean + shannon.sd), width=.05,
                 position=position_dodge(0.05)) +
  theme(strip.text.y = element_text(size = 8, hjust = 0.5,
          vjust = 0.5, face = 'bold')) +
  ggtitle("Copepoda")
Cop.a.div.thru.time
dev.copy(pdf, "phyloseq analysis/figures/Cop.a.div.thru.time.pdf", height=6, width=8)
dev.off() 

Cop.rich.thru.time <- ggplot(cop_sum_rich, aes(x=time_point, y=observed.mean, group=lake))+
  facet_grid(rows="lake") +
  ylim(10,150) +
  geom_point(size = 1.2) +
  geom_line(size = 0.3) +
  xlab('Sampling Time Point') +
  ylab('Average Richness') +
  geom_errorbar(aes(ymin=observed.mean - observed.sd, ymax=observed.mean + observed.sd), width=.05,
                 position=position_dodge(0.05)) +
theme(strip.text.y = element_text(size = 8, hjust = 0.5,
          vjust = 0.5, face = 'bold')) +
  ggtitle("Copepoda")
Cop.rich.thru.time
dev.copy(pdf, "phyloseq analysis/figures/Cop.rich.thru.time.pdf", height=6, width=8)
dev.off() 


###
rich.unrare <- richness(otu_table(PS.fin), index="observed")
div.unrare <- diversity(otu_table(PS.fin), index="shannon")

sample.a.diversity <- cbind(rich.unrare, div.unrare)
sample.a.diversity$sequencing_ID <- rownames(div.unrare)


sample.a.diversity <- cbind(sample.a.diversity, sample_data(PS.fin)[,c(4,7,8,9,22)])

water_sum_div <- summaryBy(shannon ~ sample_type*time_point, data = sample.a.diversity, FUN = c(mean, sd))
water_sum_rich <- summaryBy(observed ~ sample_type*time_point, data = sample.a.diversity, FUN = c(mean, sd))

unrare_div_lm <- lm(shannon ~ lake*time_point, data = sample.a.diversity)
Anova(unrare_div_lm)

unrare_rich_lm <- lm(observed ~ lake*time_point, data = sample.a.diversity)
Anova(unrare_rich_lm)

sample.a.div.thru.time <- ggplot(water_sum_div, aes(x=time_point, y=shannon.mean, group=sample_type))+
  facet_grid(rows="sample_type") +
  ylim(1,5) +
  geom_point(size = 1.2) +
  geom_line(size = 0.3) +
  xlab('Sampling Time Point') +
  ylab('Average Shannon Diversity') +
  geom_errorbar(aes(ymin=shannon.mean - shannon.sd, ymax=shannon.mean + shannon.sd), width=.05,
                 position=position_dodge(0.05)) +
  theme(strip.text.y = element_text(size = 8, hjust = 0.5,
          vjust = 0.5, face = 'bold')) +
  ggtitle("Comparing sample types")
sample.a.div.thru.time
dev.copy(pdf, "phyloseq analysis/figures/sample.a.div.thru.time.pdf", height=6, width=8)
dev.off() 

my_lm <- lm(shannon ~ sample_type*time_point, data = sample.a.diversity)
anova(my_lm)

 sample.rich.thru.time <- ggplot(water_sum_rich, aes(x=time_point, y=observed.mean, group=sample_type))+
  facet_grid(rows="sample_type") +
  ylim(10,150) +
  geom_point(size = 1.2) +
  geom_line(size = 0.3) +
  xlab('Sampling Time Point') +
  ylab('Average Richness') +
  geom_errorbar(aes(ymin=observed.mean - observed.sd, ymax=observed.mean + observed.sd), width=.05,
                 position=position_dodge(0.05)) +
theme(strip.text.y = element_text(size = 8, hjust = 0.5,
          vjust = 0.5, face = 'bold')) +
  ggtitle("Comparing sample types")
sample.rich.thru.time
dev.copy(pdf, "phyloseq analysis/figures/sample.rich.thru.time.pdf", height=6, width=8)
dev.off() 



```


```{r correlations}
install.packages("corrr")
library('corrr')





# cor.test(metadata$elevation_m, metadata$DOC)

ggscatter(sample_data(PS.500), x = "elevation_m", y = "DOC", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "elevation (m)", ylab = "DOC")

ggscatter(sample_data(PS.500), x = "elevation_m", y = "chla_ug.L", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "elevation (m)", ylab = "chla")


ggscatter(sample_data(PS.500), x = "elevation_m", y = "temp_C", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "elevation (m)", ylab = "Temperature (C)")


ggscatter(sample_data(PS.500), x = "latitude", y = "temp_C", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "latitude", ylab = "Temperature")

ggscatter(sample_data(PS.500), x = "latitude", y = "DOC", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "latitude", ylab = "DOC")


ggscatter(sample_data(PS.500), x = "latitude", y = "chla_ug.L", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "latitude", ylab = "chla")



```



```{r environmental correlations anova/permanova and PCA}



colSums(is.na(metadata))
# As stated early in the article, PCA only works with numerical values
numerical_data <- metadata[,10:19]
data_normalized <- scale(numerical_data)
head(data_normalized)
corr_matrix <- cor(data_normalized)
ggcorrplot(corr_matrix)
data.pca <- princomp(corr_matrix)
summary(data.pca)
fviz_eig(data.pca, addlabels = TRUE)
fviz_pca_var(data.pca, col.var = "black")


one.way.chla <- aov(chla_ug.L ~ lake*time_point, data = metadata)
summary(one.way.chla)

one.way.DOC <- aov(DOC ~ lake*time_point, data = metadata)
summary(one.way.DOC)

one.way.DO <- aov(DO_perc ~ lake*time_point, data = metadata)
summary(one.way.DO)

one.way.pH <- aov(pH ~ lake*time_point, data = metadata)
summary(one.way.pH)


env.model.chla <- adonis2(bc_500 ~ chla_ug.L, data = nmds.merge2, permutations = 1000)
env.model.chla

env.model.DOC <- adonis2(bc_zoops ~ DOC, data = nmds.merge3, permutations = 1000)
env.model.DOC

env.model.DO <- adonis2(bc_500 ~ DO_perc, data = nmds.merge2, permutations = 1000)
env.model.DO

env.model.temp <- adonis2(bc_500 ~ temp_C, data = nmds.merge2, permutations = 1000)
env.model.temp

env.model.pH <- adonis2(bc_500 ~ pH, data = nmds.merge2, permutations = 1000)
env.model.pH

env.model.cond <- adonis2(bc_500 ~ cond, data = nmds.merge2, permutations = 1000)
env.model.cond

env.model.lat <- adonis2(bc_500 ~ latitude, data = nmds.merge2, permutations = 1000)
env.model.lat

env.model.elev <- adonis2(bc_500 ~ elevation_m, data = nmds.merge2, permutations = 1000)
env.model.elev
```



```{r T tests}
temps <- unique(metadata$temp_C)
t.test(x = temps)

```




```{r Bray curtis distance matrix}

raw.asv.table <- as.data.frame(t(otu_table(PS.fin)))
str(raw.asv.table)
str(ASV_table)

# 3 methods for calculating bray curtis dissimilarity

set.seed(10000)
avg_bray_500 <- avgdist(raw.asv.table, sample = 500)
str(avg_bray_500) # should be type 'dist'

set.seed(10000)
bc_vegdist <- vegdist(t(otu_table(PS.fin)), method = "bray")


set.seed(10000)
bc <- phyloseq::distance(PS.fin, method = "bray")
set.seed(10000)
bc_500 <- phyloseq::distance(PS.500, method = "bray")
set.seed(10000)
bc_zoops <- phyloseq::distance(PS.zoops, method = "bray")
set.seed(10000)
bc_water <- phyloseq::distance(PS.water, method = "bray")

```



```{r PERMANOVAS from distance matrix}

# run NMDS, euclidean distance because different scales
set.seed(10000)
nmds1 <- metaMDS(bc,
          distance = "bray",
          k = 3,
          maxit = 999, 
          wascores = TRUE)

species.scores <- as.data.frame(scores(nmds1, display="site"))
nmds.merge1 <- merge(sample_data(PS.fin), species.scores, by = 'row.names', all = TRUE)
nmds.merge1$basin <- as.factor(ifelse(nmds.merge1$lake == "Eastern Brook" | nmds.merge1$lake == "Serene" | nmds.merge1$lake == "Convict", "South", "North"))

broad.model <- adonis2(bc ~ lake*time_point*sample_type, data = nmds.merge1, permutations = 1000)
broad.model


set.seed(10000)
nmds2 <- metaMDS(bc_500,
          distance = "bray",
          k = 3,
          maxit = 999, 
          wascores = TRUE)

NMDS1=nmds2$points[,1]
NMDS2=nmds2$points[,2]


species.scores <- as.data.frame(scores(nmds2, display="site"))
nmds.merge2 <- merge(sample_data(PS.500), species.scores, by = 'row.names', all = TRUE)
nmds.merge2$basin <- as.factor(ifelse(nmds.merge2$lake == "Eastern Brook" | nmds.merge2$lake == "Serene" | nmds.merge2$lake == "Convict", "South", "North"))

broad.model2 <- adonis2(bc_500 ~ lake*time_point + sample_type, data = nmds.merge2, permutations = 1000)
broad.model2



#test for beta dispersion
anova(betadisper(bc_500, nmds.merge2$time_point)) # not significant
anova(betadisper(bc_500, nmds.merge2$sample_type)) # not significant

set.seed(10000)
nmds3 <- metaMDS(bc_zoops,
          distance = "bray",
          k = 3,
          maxit = 999, 
          wascores = TRUE)

species.scores <- as.data.frame(scores(nmds3, display="site"))
nmds.merge3 <- merge(sample_data(PS.zoops), species.scores, by = 'row.names', all = TRUE)
nmds.merge3$basin <- as.factor(ifelse(nmds.merge3$lake == "Eastern Brook" | nmds.merge3$lake == "Serene" | nmds.merge3$lake == "Convict", "South", "North"))

broad.model3 <- adonis2(bc_zoops ~ time_point + lake + phy_group, data = nmds.merge3, permutations = 1000)
broad.model3




set.seed(10000)
nmds4 <- metaMDS(bc_water,
          distance = "bray",
          k = 3,
          maxit = 999, 
          wascores = TRUE)

species.scores <- as.data.frame(scores(nmds4, display="site"))
nmds.merge4 <- merge(sample_data(PS.water), species.scores, by = 'row.names', all = TRUE)
nmds.merge4$region <- as.factor(ifelse(nmds.merge4$lake == "Eastern Brook" | nmds.merge4$lake == "Serene" | nmds.merge4$lake == "Convict", "South", "North"))

broad.model4 <- adonis2(bc_water ~ lake + time_point, data = nmds.merge4, permutations = 1000)
broad.model4

# testing for significance in beta dispersion, test whether the effects you're 
# finding in the adonis2 are actually due to a difference in variance.
# time is not significant
anova(betadisper(bc_zoops, nmds.merge3$time_point))

anova(betadisper(bc, nmds2.merge$phy_group))



```



```{r combining NMDS and PCA}
#Take environmental data, run PCA to compress to a single variable (PC1), and examine
#relationship between PC1 and NMDS1, as a way to examine beta diversity x environment. 
#Output here are testing NMDS relationship against PC1 and habitat using linear models.

numerical_data <- metadata_500[,9:18]
env.PCA <- prcomp(numerical_data, center = TRUE, scale= TRUE) 
PC.summary<-(summary(env.PCA))
newdat<-env.PCA$x[,1:4]

############### PCA and NMDS combine
NMDS.otu<-as.data.frame(NMDS1) # NMDS Bray Curtis of OTUs
PCA.env<-as.data.frame(newdat) # the exported data from PCA of environment
PC.NMD<-merge(PCA.env, NMDS.otu, by = "row.names", all = TRUE) # merge dataframes
PC.NMD<-na.omit(PC.NMD) #drop NA columns that don't correspond
colnames(PC.NMD)[1]<-"sampleID"


# need help with adding a column like time point or lake
time_colors <- scale_color_manual(values = c("royalblue1", "chartreuse3", "chocolate1", "deeppink2", "purple"))


## Tests for relationship pf PC x NMDS
# full model
mod<-lm(NMDS1~PC1, data=PC.NMD)
print(anova(mod), digits=6)

### formatting
BW.back<-theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
               panel.background = element_blank(), axis.line = element_line(colour = "black", size=0.2))
### ### ### ### ### ### 
### plot of NMDS-1 x PC1
PC.NMDS.plot<-ggplot(data=PC.NMD, aes(x=PC1, y=NMDS1, color=time_colors))+
  geom_point(aes(color=time_colors), alpha=.7) + 
  xlab("PC1") +
  ylab("NMDS1 (Bray-Curtis)") +
  theme_bw()+
  geom_smooth(aes(color=time_colors, fill=time_colors), values=, method = "lm", alpha = .2, size=0.6) +
  theme(legend.position="top", legend.title = element_blank(),
        axis.text=element_text(size=6),
        axis.title=element_text(size=10))
PC.NMDS.plot
dev.copy(pdf, "phyloseq analysis/figures.pdf", height=3, width=6)
dev.off()
```





```{r envfit}

#Fit environmental vectors to ordination to see which environmental variables are correlated with the ordination

#environmental variables, continuous
env <- sample_data(PS.fin)[ ,c(9:12,14,16,18)]
env500 <- sample_data(PS.500)[ ,c(10,11,14,16,18)]
envzoops <- sample_data(PS.zoops)[ ,c(9:14,16,18)]



# factors, categorical
facs <- sample_data(PS.fin)[,c(7,9)]
facs500 <- sample_data(PS.500)[,c(7,9)]
facszoops <- sample_data(PS.zoops)[,c(7,9)]

fit.env <- envfit(nmds1, env, na.rm = T)
fit.env500 <- envfit(nmds2, env500, na.rm = T)
fit.envzoops <- envfit(nmds3, envzoops, na.rm = T)

NMDS.plot.df=data.frame(NMDS1=NMDS1,NMDS2=NMDS2, metadata_500[,6])
times <- NMDS.plot.df$time_point
levels(NMDS.plot.df$time_point)

# colors and groups for plots
time_colors <- scale_color_manual(values = c("royalblue1", "chartreuse3", "chocolate1", "deeppink2", "khaki4"))


### make plot by habitat with vectors for environment
environm_plot<-ordiplot(nmds2, type="n", main=substitute(paste("")), cex.main=1, display="sites", xlim=c(-0.25, 0.8), cex.lab=0.8, cex.axis=0.8)
abline(h = 0, lty = "dotted")
abline(v = 0, lty = "dotted")
points(nmds2, "sites", cex=0.8, pch=16, col=times)
ordiellipse(nmds2, groups=times, kind="sd", draw="polygon", conf=0.95, alpha=30, col = times, border = times)
legend("topright", legend=levels(times), cex=1, pch=16, col=times, pt.cex=1, bty="n")
par.new=T
plot(fit.env500, col="black", p.max=0.05, cex=0.9, lwd=1)
dev.copy(pdf, "phyloseq analysis/figures/environm_plot.pdf", height=5.5, width=6)
dev.off() 

data.scores <- as.data.frame(scores(nmds1))
data.scores.df <- cbind(facs, data.scores)
data.scores500 <- as.data.frame(scores(nmds2))
data.scores.df500 <- cbind(facs500, data.scores500)
data.scores1000 <- as.data.frame(scores(nmds3))
data.scores.df1000 <- cbind(facs1000, data.scores1000)


en_coord_cont = as.data.frame(scores(fit.env, "vectors")) * ordiArrowMul(fit.env)
en_coord_cat = as.data.frame(scores(fit.env, "factors")) * ordiArrowMul(fit.env)
en_coord_cont500 = as.data.frame(scores(fit.env500, "vectors")) * ordiArrowMul(fit.env500)
en_coord_cat500 = as.data.frame(scores(fit.env500, "factors")) * ordiArrowMul(fit.env500)
en_coord_cont1000 = as.data.frame(scores(fit.env1000, "vectors")) * ordiArrowMul(fit.env1000)
en_coord_cat1000 = as.data.frame(scores(fit.env1000, "factors")) * ordiArrowMul(fit.env1000)


envfit_plot = ggplot(data = data.scores.df, aes(x = NMDS1, y = NMDS2)) + 
     geom_point(data = data.scores.df, aes(colour = lake), size = 3, alpha = 0.5) + 
     scale_colour_manual(values = c("orange", "steelblue", "maroon", "mediumseagreen", "coral", "pink"))  + 
     geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
       data = en_coord_cont, size = 1, arrow = arrow(length = unit(0.25, "cm")),
       alpha = 0.5, colour = "black") +
     geom_point(data = en_coord_cat, aes(x = NMDS1, y = NMDS2), 
       shape = "diamond", size = 4, alpha = 0.6, colour = "navy") +
     geom_text(data = en_coord_cat, aes(x = NMDS1, y = NMDS2+0.04), 
       label = row.names(en_coord_cat), colour = "navy", fontface = "bold") + 
     geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "black", 
       fontface = "bold", label = row.names(en_coord_cont)) + 
     stat_ellipse(aes(colour = lake)) +
     theme(axis.title = element_text(size = 10, face = "bold", colour = "black"), 
       panel.background = element_blank(), panel.border = element_rect(fill = NA, colour = "black"), 
       axis.ticks = element_blank(), axis.text = element_blank(), legend.key = element_blank(), 
       legend.title = element_text(size = 10, face = "bold", colour = "black"), 
       legend.text = element_text(size = 9, colour = "black")) + 
     labs(colour = "lake")
     
envfit_plot
dev.copy(pdf, "phyloseq analysis/figures/envfit_plot.pdf", height=4, width=5)
dev.off() 




envfit_plot500 = ggplot(data = data.scores.df500, aes(x = NMDS1, y = NMDS2)) + 
     geom_point(data = data.scores.df500, aes(colour = lake), size = 3, alpha = 0.5) + 
     scale_colour_manual(values = c("orange", "steelblue", "maroon", "mediumseagreen", "coral", "pink"))  + 
     geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
       data = en_coord_cont500, size = 1, arrow = arrow(length = unit(0.25, "cm")),
       alpha = 0.5, colour = "black") +
     geom_point(data = en_coord_cat500, aes(x = NMDS1, y = NMDS2), 
       shape = "diamond", size = 4, alpha = 0.6, colour = "navy") +
     geom_text(data = en_coord_cat500, aes(x = NMDS1, y = NMDS2+0.04), 
       label = row.names(en_coord_cat500), colour = "navy", fontface = "bold") + 
     geom_text(data = en_coord_cont500, aes(x = NMDS1, y = NMDS2), colour = "black", 
       fontface = "bold", label = row.names(en_coord_cont500)) + 
     stat_ellipse(aes(colour = lake)) +
     theme(axis.title = element_text(size = 10, face = "bold", colour = "black"), 
       panel.background = element_blank(), panel.border = element_rect(fill = NA, colour = "black"), 
       axis.ticks = element_blank(), axis.text = element_blank(), legend.key = element_blank(), 
       legend.title = element_text(size = 10, face = "bold", colour = "black"), 
       legend.text = element_text(size = 9, colour = "black")) + 
     labs(colour = "lake")
     
envfit_plot500
dev.copy(pdf, "phyloseq analysis/figures/envfit_plot500.pdf", height=4, width=5)
dev.off() 





envfit_plot1000 = ggplot(data = data.scores.df1000, aes(x = NMDS1, y = NMDS2)) + 
     geom_point(data = data.scores.df1000, aes(colour = lake), size = 3, alpha = 0.5) + 
     scale_colour_manual(values = c("orange", "steelblue", "maroon", "mediumseagreen", "coral", "pink"))  + 
     geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
       data = en_coord_cont1000, size = 1, arrow = arrow(length = unit(0.25, "cm")),
       alpha = 0.5, colour = "black") +
     geom_point(data = en_coord_cat1000, aes(x = NMDS1, y = NMDS2), 
       shape = "diamond", size = 4, alpha = 0.6, colour = "navy") +
     geom_text(data = en_coord_cat1000, aes(x = NMDS1, y = NMDS2+0.04), 
       label = row.names(en_coord_cat1000), colour = "navy", fontface = "bold") + 
     geom_text(data = en_coord_cont1000, aes(x = NMDS1, y = NMDS2), colour = "black", 
       fontface = "bold", label = row.names(en_coord_cont1000)) + 
     stat_ellipse(aes(colour = lake))+
     theme(axis.title = element_text(size = 10, face = "bold", colour = "black"), 
       panel.background = element_blank(), panel.border = element_rect(fill = NA, colour = "black"), 
       axis.ticks = element_blank(), axis.text = element_blank(), legend.key = element_blank(), 
       legend.title = element_text(size = 10, face = "bold", colour = "black"), 
       legend.text = element_text(size = 9, colour = "black")) + 
     labs(colour = "lake")
     
envfit_plot1000
dev.copy(pdf, "phyloseq analysis/figures/envfit_plot1000.pdf", height=4, width=5)
dev.off() 

plot(nmds1)
plot(fit.env)


ordiplot(nmds1, type = "points")
orditorp(nmds1, display = "sites", labels = F)
plot(fit.env, p.max = 0.01, col = "black", cex = 0.7)
```



```{r ordiR2step}
# capscale is partial distance-based redundancy analysis

# bray-curtis distance matrix


# define scope, fit global model
dbrda <- capscale(bc_vegdist ~ time_point + lake + phy_group + DOC + temp_C, data = nmds2.merge, distance = "euclidean")
set.seed(1999) 
upr <- dbrda(bc ~ . + I(temp_C)^2 + I(elevation_m)^2 + I(chla_ug.L)^2 + 
               I(DOC)^2 + I(longitude)^2 + I(latitude)^2 + I(DO_perc)^2 +
               I(spc)^2 + I(cond)^2 + I(pH)^2, data = nmds2.merge)
lwr <- dbrda(bc_vegdist ~ 1, data = global_df, na.action = 'na.omit')
mod_selec <- ordiR2step(lwr, scope = formula(upr))
anova(mod_selec)# selecting site as most important factor - good stuff honestly simple semi strong model here 
anova(mod_selec, by = "axis")
RsquareAdj(mod_selec)
screeplot(mod_selec)

# performing stepwise selection with ordiRstep
ordiR2step(dbrda, )

```

```{r AIC and bioenv}

AIC()

env.cont <-  metadata_500[ ,c(10:19)]
bioenv(comm = bc, env = env.cont, upto = ncol(env.cont))

```


```{r mantel test, geographic distance}
install.packages("fossil")
library(fossil)

# to calculate geographic distances between lakes

gps <- as.data.frame(cbind(sample_data(PS.fin)$latitude, sample_data(PS.fin)$longitude))
geodists_km <- earth.dist(gps[,1:2], dist = T)
str(geodists_km)
mat_geodists_km <- as.matrix(geodists_km)
str(mat_geodists_km)
rownames(mat_geodists_km) <- rownames(sample_data(PS.fin))
colnames(mat_geodists_km) <- t(rownames(sample_data(PS.fin)))


# to calculate bray curtis distance
study_bc_mat <- as.matrix(vegdist(t(raw.asv.table), "bray"))
str(study_bc_mat)
all_otu.dist <- phyloseq::distance(sample_data(PS.fin), "bray")

# mantel distance decay
# spatial effects on community dissimilarity were tested using distance between samples in meters and the bray curtis dissimilarity matrix
#To run a Mantel test, we will need to generate two distance matrices: one containing spatial 
#distances and one containing Bray-Curtis distances between samples at the given points.  In the 
#spatial distance matrix, entries for pairs of points that are close together are lower than for 
#pairs of points that are far apart.  In the BC matrix, entries for pairs of locations 
#with similar outcomes are lower than for pairs of points with dissimilar outcomes.  We do this 
#using the dist function.  The Mantel test function will require objects of this "distance" class.
mantel_test <- mantel(study_bc_mat ~ mat_geodists_km)

Study.df <- data.frame(Distance = mat_geodists_km[lower.tri(mat_geodists_km)],
           BrayCurtis = study_bc_mat[lower.tri(study_bc_mat)])
dim(mat_geodists_km)
dim(study_bc_mat)
rownames(mat_geodists_km)
rownames(study_bc_mat)
colnames(mat_geodists_km[lower.tri(mat_geodists_km)])

Study_dist_plot <- ggplot(Study.df, aes(x=Distance, y=BrayCurtis)) +
  geom_point(size=0.8,alpha=0.5) +
  geom_smooth(method = "glm", formula = y~x) +
  scale_y_continuous(name="Bray-Curtis Dissimilarity",breaks=seq(0,1,0.25),limits=c(0,1)) +
  scale_x_continuous(name="Distance (km)",breaks=seq(0,8,2),limits=c(0,8)) +
  theme(plot.title = element_text(size=10, hjust = 0.5),
        axis.text.x=element_text(colour="black",size=7), 
        axis.title.x=element_blank(),
        axis.text.y=element_text(colour="black",size=7),
        axis.title=element_text(colour="black",size=9),
        legend.title=element_text(colour="black",size=7,face="bold"),
        legend.text=element_text(colour="black",size=7),
        panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
        panel.background=element_blank())

mantel.mod<-lm(BrayCurtis~log(Distance+1), data=Study.df)
```




```{r MDS plots by time point}
T1 <- subset_samples(PS.fin, time_point=="1")
ORD.T1 <- ordinate(T1, method='MDS', distance='bray')

MDS.ord.T1 <- plot_ordination(
  physeq = T1,                                                   
  ordination = ORD.T1) +                                                
  geom_point(aes(color = lake, shape= phy_group), size = 3) +    
  stat_ellipse(level=0.9, linetype = 2, aes(color=lake)) +
  scale_color_brewer(palette = "Dark2") +
  scale_fill_brewer(palette = "Dark2") + ggtitle("Time1") + theme_classic()

MDS.ord.T1
dev.copy(pdf, "phyloseq analysis/figures/MDS.ord.T1.pdf", height=6, width=7)
dev.off() 





T2<- subset_samples(PS.fin, time_point=="2")
ORD.T2 <- ordinate(T2, method='MDS', distance='bray')

MDS.ord.T2<-plot_ordination(
  physeq = T2,                                                   
  ordination = ORD.T2) +                                                
  geom_point(aes(color = lake, shape= phy_group), size = 3) +    
  stat_ellipse(level=0.9, linetype = 2, aes(color=lake)) +
  scale_color_brewer(palette = "Dark2") +
  scale_fill_brewer(palette = "Dark2") + ggtitle("Time2") +
  theme_classic()     

MDS.ord.T2
dev.copy(pdf, "phyloseq analysis/figures/MDS.ord.T2.pdf", height=6, width=7)
dev.off() 






T3<- subset_samples(PS.fin, time_point=="3")
ORD.T3 <- ordinate(T3, method='MDS', distance='bray')

MDS.ord.T3<-plot_ordination(
  physeq = T3,                                                   
  ordination = ORD.T3) +                                                
  geom_point(aes(color = lake, shape= phy_group), size = 3) +    
  stat_ellipse(level=0.9, linetype = 2, aes(color=lake)) +
  scale_color_brewer(palette = "Dark2") +
  scale_fill_brewer(palette = "Dark2") + ggtitle("Time3") +
  theme_classic()     

MDS.ord.T3
dev.copy(pdf, "phyloseq analysis/figures/MDS.ord.T3.pdf", height=6, width=7)
dev.off() 





T4<- subset_samples(PS.fin, time_point=="4")
ORD.T4 <- ordinate(T4, method='MDS', distance='bray')

MDS.ord.T4<-plot_ordination(
  physeq = T4,                                                   
  ordination = ORD.T4) +                                                
  geom_point(aes(color = lake, shape= phy_group), size = 3) +    
  stat_ellipse(level=0.9, linetype = 2, aes(color=lake)) +
  scale_color_brewer(palette = "Dark2") +
  scale_fill_brewer(palette = "Dark2") + ggtitle("Time4") +
  theme_classic()     

MDS.ord.T4
dev.copy(pdf, "phyloseq analysis/figures/MDS.ord.T4.pdf", height=6, width=7)
dev.off() 





T5 <- subset_samples(PS.fin, time_point=="5")
ORD.T5 <- ordinate(T5, method='MDS', distance='bray')

MDS.ord.T5 <- plot_ordination(
  physeq = T5,                                                   
  ordination = ORD.T5) +                                                
  geom_point(aes(color = lake, shape= phy_group), size = 3) +    
  stat_ellipse(level=0.9, linetype = 2, aes(color=lake)) +
  scale_color_brewer(palette = "Dark2") +
  scale_fill_brewer(palette = "Dark2") + ggtitle("Time5") +
  theme_classic()     

MDS.ord.T5
dev.copy(pdf, "phyloseq analysis/figures/MDS.ord.T5.pdf", height=6, width=7)
dev.off() 

install.packages("patchwork")
library("patchwork")
library("ggpubr")
library(cowplot)

combined.mds <- ggarrange(MDS.ord.T1 + theme(axis.title.y=element_text(size=8)),
          MDS.ord.T2 + theme(axis.title.y=element_text(size=8)),
          MDS.ord.T3 + theme(axis.title.y=element_text(size=8)),
          MDS.ord.T4 + theme(axis.title.y=element_text(size=8)),
          MDS.ord.T5 + theme(axis.title.y=element_text(size=8)),
          plot_layout(guides="collect"), labels=NULL, common.legend = TRUE, 
          legend="bottom", align="hv", 
          font.label = list(size=10, color="black", family=NULL, position="top", labels="auto"))
combined.mds
dev.print(pdf, "phyloseq analysis/figures/combined.mds.pdf", height=10, width=15)
dev.off

 
```



```{r NMDS phy_group by time point}
centroid <- nmds.merge2 %>% 
  group_by(time_point) %>%
  summarize(NMDS1 = mean(NMDS1), NMDS2 = mean(NMDS2))
str(nmds2.merge)

nmds.elev <- ggplot(nmds.merge3, aes(x=NMDS1, y=NMDS2)) +
  geom_point(aes(color = elev.cat), size = 2.5) +
  stat_ellipse(level=0.9, lwd = 1, linetype = 2, aes(color = elev.cat)) +
  theme_bw() + theme(legend.key.size = unit(2, 'cm'), legend.text = element_text(size=20), legend.title = element_text(size=22))
nmds.elev
dev.print(pdf, "phyloseq analysis/figures/nmds.elev.pdf", height=10, width=15)
dev.off

nmds.basin <- ggplot(nmds.merge3, aes(x=NMDS1, y=NMDS2)) +
  geom_point(aes(color = basin), size = 2.5) +
  stat_ellipse(level=0.9, lwd = 1, linetype = 2, aes(color = basin)) +
  theme_bw() + theme(legend.key.size = unit(2, 'cm'), legend.text = element_text(size=20), legend.title = element_text(size=22))
nmds.basin
dev.print(pdf, "phyloseq analysis/figures/nmds.basin.pdf", height=10, width=15)
dev.off

nmds.convict <- ggplot(nmds.merge3[nmds.merge3$lake == "Convict", ], aes(x=NMDS1, y=NMDS2)) +
  geom_point(aes(color = time_point), size = 2.5) +
  stat_ellipse(level=0.9, lwd = 0.7, linetype = 1, aes(color = time_point)) +
  scale_color_manual(values = c("orangered", "turquoise2", "navy", "violetred", "lightslateblue")) +
  theme_bw() + ggtitle("Convict")
nmds.convict
dev.print(pdf, "phyloseq analysis/figures/nmds.convict.pdf", height=10, width=15)
dev.off

nmds.convict.water <- ggplot(nmds.merge4[nmds.merge4$lake == "Convict", ], aes(x=NMDS1, y=NMDS2)) +
  geom_point(aes(color = time_point), size = 2.5) +
  stat_ellipse(level=0.9, lwd = 0.7, linetype = 1, aes(color = time_point)) +
  scale_color_manual(values = c("orangered", "turquoise2", "navy", "violetred", "lightslateblue")) +
  theme_bw() + ggtitle("Convict")
nmds.convict.water
dev.print(pdf, "phyloseq analysis/figures/nmds.convict.water.pdf", height=10, width=15)
dev.off

nmds.east.brook <- ggplot(nmds.merge3[nmds.merge3$lake == "Eastern Brook", ], aes(x=NMDS1, y=NMDS2)) +
  geom_point(aes(color = time_point, shape = sample_type), size = 2.5) +
  stat_ellipse(level=0.9, lwd = 0.7, linetype = 1, aes(color = time_point)) +
  scale_color_manual(values = c("orangered", "turquoise2", "navy", "violetred", "lightslateblue")) +
  theme_bw() + ggtitle("Eastern Brook")
nmds.east.brook
dev.print(pdf, "phyloseq analysis/figures/nmds.east.brook.pdf", height=10, width=15)
dev.off

nmds.serene <- ggplot(nmds.merge3[nmds.merge3$lake == "Serene", ], aes(x=NMDS1, y=NMDS2)) +
  geom_point(aes(color = time_point, shape = sample_type), size = 2.5) +
  stat_ellipse(level=0.9, lwd = 0.7, linetype = 1, aes(color = time_point)) +
  scale_color_manual(values = c("orangered", "turquoise2", "navy", "violetred", "lightslateblue")) +
  theme_bw() + ggtitle("Serene")
nmds.serene
dev.print(pdf, "phyloseq analysis/figures/nmds.serene.pdf", height=10, width=15)
dev.off

nmds.cooney <- ggplot(nmds.merge3[nmds.merge3$lake == "Cooney", ], aes(x=NMDS1, y=NMDS2)) +
  geom_point(aes(color = time_point, shape = sample_type), size = 2.5) +
  stat_ellipse(level=0.9, lwd = 0.7, linetype = 1, aes(color = time_point)) +
  scale_color_manual(values = c("orangered", "turquoise2", "navy", "violetred", "lightslateblue")) +
  theme_bw() + ggtitle("Cooney")
nmds.cooney
dev.print(pdf, "phyloseq analysis/figures/nmds.cooney.pdf", height=10, width=15)
dev.off

nmds.blue <- ggplot(nmds.merge3[nmds.merge3$lake == "Blue", ], aes(x=NMDS1, y=NMDS2)) +
  geom_point(aes(color = time_point, shape = sample_type), size = 2.5) +
  stat_ellipse(level=0.9, lwd = 0.7, linetype = 1, aes(color = time_point)) +
  scale_color_manual(values = c("orangered", "turquoise2", "navy", "violetred", "lightslateblue")) +
  theme_bw() + ggtitle("Blue")
nmds.blue
dev.print(pdf, "phyloseq analysis/figures/nmds.blue.pdf", height=10, width=15)
dev.off

nmds.virginia <- ggplot(nmds.merge3[nmds.merge3$lake == "Virginia", ], aes(x=NMDS1, y=NMDS2)) +
  geom_point(aes(color = time_point, shape = sample_type), size = 2.5) +
  stat_ellipse(level=0.9, lwd = 0.7, linetype = 1, aes(color = time_point)) +
  scale_color_manual(values = c("orangered", "turquoise2", "navy", "violetred", "lightslateblue")) +
  theme_bw() + ggtitle("Virginia")
nmds.virginia
dev.print(pdf, "phyloseq analysis/figures/nmds.virginia.pdf", height=10, width=15)
dev.off

combined.nmds.lakes <- ggarrange(nmds.convict + theme(axis.title.y=element_text(size=8)),
          nmds.east.brook + theme(axis.title.y=element_text(size=8)),
          nmds.serene + theme(axis.title.y=element_text(size=8)),
          nmds.cooney + theme(axis.title.y=element_text(size=8)),
          nmds.blue + theme(axis.title.y=element_text(size=8)),
          nmds.virginia + theme(axis.title.y=element_text(size=8)),
          plot_layout(guides="collect"), labels=NULL, common.legend = TRUE, 
          legend="bottom", align="hv", 
          font.label = list(size=10, color="black", family=NULL, position="top", labels="auto"))
combined.nmds.lakes
dev.print(pdf, "phyloseq analysis/figures/combined.nmds.lakes.pdf", height=10, width=15)
dev.off

nmds.cladocera.time.lake <- ggplot(nmds.merge2[nmds.merge2$phy_group == "cladocera", ], aes(x=NMDS1, y=NMDS2)) +
  geom_point(aes(color = time_point)) +
  stat_ellipse(level=0.9, linetype = 2, aes(color = time_point)) +
  theme_bw() +
  ggtitle("Cladocera")
nmds.cladocera.time.lake

nmds.copepoda.time.lake <- ggplot(nmds.merge3[nmds.merge3$phy_group == "copepoda", ], aes(x=NMDS1, y=NMDS2)) +
  geom_point(aes(color = time_point), size = 3) +
  stat_ellipse(level=0.9, linetype = 2, aes(color = time_point)) +
  theme_bw() +
  ggtitle("Copepoda")
nmds.copepoda.time.lake

nmds.water.time.lake <- ggplot(nmds.merge4, aes(x=NMDS1, y=NMDS2)) +
  geom_point(aes(shape = region), size = 3) +
  stat_ellipse(level=0.9, linetype = 2, aes(color = time_point)) +
  theme_bw() +
  ggtitle("Water")
nmds.water.time.lake

nmds.zoops.time.basin <- ggplot(nmds.merge3, aes(x=NMDS1, y=NMDS2, color = time_point)) +
  geom_point(aes(color = basin)) +
  stat_ellipse(level=0.9, linetype = 2) +
  theme_bw() +
  ggtitle("Zoops")
nmds.zoops.time.basin
  
test_nmds1 <- ggplot(nmds.merge1[(nmds.merge1$time_point == "1"), ], aes(x=NMDS1, y=NMDS2, color = basin)) +
  geom_point(aes(color = basin, shape = phy_group), size = 3) + 
  stat_ellipse(level=0.9, linetype = 2, aes(color = basin)) +
  ggtitle("Time 1") +
  theme_bw()
test_nmds1

test_nmds2 <- ggplot(nmds.merge1[(nmds.merge1$time_point == "2"), ], aes(x=NMDS1, y=NMDS2, color = basin)) +
   geom_point(aes(color = basin, shape = phy_group), size = 3) + 
   stat_ellipse(level=0.9, linetype = 2, aes(color = basin)) +
   ggtitle("Time 2") +
   theme_bw()
test_nmds2

test_nmds3 <- ggplot(nmds.merge1[(nmds.merge1$time_point == "3"), ], aes(x=NMDS1, y=NMDS2, color = basin)) +
  geom_point(aes(color = basin, shape = phy_group), size = 3) + 
  stat_ellipse(level=0.9, linetype = 2, aes(color = basin)) +
  ggtitle("Time 3") +
  theme_bw()
test_nmds3

test_nmds4 <- ggplot(nmds.merge1[(nmds.merge1$time_point == "4"), ], aes(x=NMDS1, y=NMDS2, color = basin)) +
   geom_point(aes(color = basin, shape = phy_group), size = 3) + 
   stat_ellipse(level=0.9, linetype = 2, aes(color = basin)) +
   ggtitle("Time 4") +
   theme_bw()
test_nmds4

test_nmds5 <- ggplot(nmds.merge1[(nmds.merge1$time_point == "5"), ], aes(x=NMDS1, y=NMDS2, color = basin)) +
   geom_point(aes(color = basin, shape = phy_group), size = 3) + 
   stat_ellipse(level=0.9, linetype = 2, aes(color = basin)) +
   ggtitle("Time 5") +
   theme_bw()
test_nmds5

# now by elevation category

test_nmds6 <- ggplot(nmds.merge1[(nmds.merge1$time_point == "1"), ], aes(x=NMDS1, y=NMDS2, color = elev.cat)) +
  geom_point(aes(color = elev.cat, shape = phy_group), size = 3) + 
  stat_ellipse(level=0.9, linetype = 2, aes(color = elev.cat)) +
  ggtitle("Time 1") +
  theme_bw()
test_nmds6

test_nmds7 <- ggplot(nmds.merge1[(nmds.merge1$time_point == "2"), ], aes(x=NMDS1, y=NMDS2, color = elev.cat)) +
   geom_point(aes(color = elev.cat, shape = phy_group), size = 3) + 
   stat_ellipse(level=0.9, linetype = 2, aes(color = elev.cat)) +
   ggtitle("Time 2") +
   theme_bw()
test_nmds7

test_nmds8 <- ggplot(nmds.merge1[(nmds.merge1$time_point == "3"), ], aes(x=NMDS1, y=NMDS2, color = elev.cat)) +
  geom_point(aes(color = elev.cat, shape = phy_group), size = 3) + 
  stat_ellipse(level=0.9, linetype = 2, aes(color = elev.cat)) +
  ggtitle("Time 3") +
  theme_bw()
test_nmds8

test_nmds9 <- ggplot(nmds.merge1[(nmds.merge1$time_point == "4"), ], aes(x=NMDS1, y=NMDS2, color = elev.cat)) +
   geom_point(aes(color = elev.cat, shape = phy_group), size = 3) + 
   stat_ellipse(level=0.9, linetype = 2, aes(color = elev.cat)) +
   ggtitle("Time 4") +
   theme_bw()
test_nmds9

test_nmds10 <- ggplot(nmds.merge1[(nmds.merge1$time_point == "5"), ], aes(x=NMDS1, y=NMDS2, color = elev.cat)) +
   geom_point(aes(color = elev.cat, shape = phy_group), size = 3) + 
   stat_ellipse(level=0.9, linetype = 2, aes(color = elev.cat)) +
   ggtitle("Time 5") +
   theme_bw()
test_nmds10

# now by lake

test_nmds11 <- ggplot(nmds.merge1[(nmds.merge1$time_point == "1"), ], aes(x=NMDS1, y=NMDS2, color = lake)) +
  geom_point(aes(color = lake, shape = phy_group), size = 3) + 
  stat_ellipse(level=0.9, linetype = 2, aes(color = lake)) +
  ggtitle("Time 1") +
  theme_bw()
test_nmds11
dev.print(pdf, "phyloseq analysis/figures/test_nmds11.pdf", height=10, width=15)
dev.off

test_nmds12 <- ggplot(nmds.merge1[(nmds.merge1$time_point == "2"), ], aes(x=NMDS1, y=NMDS2, color = lake)) +
   geom_point(aes(color = lake, shape = phy_group), size = 3) + 
   stat_ellipse(level=0.9, linetype = 2, aes(color = lake)) +
   ggtitle("Time 2") +
   theme_bw()
test_nmds12
dev.print(pdf, "phyloseq analysis/figures/test_nmds12.pdf", height=10, width=15)
dev.off

test_nmds13 <- ggplot(nmds.merge1[(nmds.merge1$time_point == "3"), ], aes(x=NMDS1, y=NMDS2, color = lake)) +
  geom_point(aes(color = lake, shape = phy_group), size = 3) + 
  stat_ellipse(level=0.9, linetype = 2, aes(color = lake)) +
  ggtitle("Time 3") +
  theme_bw()
test_nmds13
dev.print(pdf, "phyloseq analysis/figures/test_nmds13.pdf", height=10, width=15)
dev.off

test_nmds14 <- ggplot(nmds.merge1[(nmds.merge1$time_point == "4"), ], aes(x=NMDS1, y=NMDS2, color = lake)) +
   geom_point(aes(color = lake, shape = phy_group), size = 3) + 
   stat_ellipse(level=0.9, linetype = 2, aes(color = lake)) +
   ggtitle("Time 4") +
   theme_bw()
test_nmds14
dev.print(pdf, "phyloseq analysis/figures/test_nmds14.pdf", height=10, width=15)
dev.off

test_nmds15 <- ggplot(nmds.merge1[(nmds.merge1$time_point == "5"), ], aes(x=NMDS1, y=NMDS2, color = lake)) +
   geom_point(aes(color = lake, shape = phy_group), size = 3) + 
   stat_ellipse(level=0.9, linetype = 2, aes(color = lake)) +
   ggtitle("Time 5") +
   theme_bw()
test_nmds15
dev.print(pdf, "phyloseq analysis/figures/test_nmds15.pdf", height=10, width=15)
dev.off

library("patchwork")
library("ggpubr")
library(cowplot)
combined.nmds.lake <- ggarrange(test_nmds11 + theme(axis.title.y=element_text(size=8)),
          test_nmds12 + theme(axis.title.y=element_text(size=8)),
          test_nmds13 + theme(axis.title.y=element_text(size=8)),
          test_nmds14 + theme(axis.title.y=element_text(size=8)),
          test_nmds15 + theme(axis.title.y=element_text(size=8)),
          plot_layout(guides="collect"), labels=NULL, common.legend = TRUE, 
          legend="bottom", align="hv", 
          font.label = list(size=10, color="black", family=NULL, position="top", labels="auto"))
combined.nmds.lake
dev.print(pdf, "phyloseq analysis/figures/combined.nmds.lake.pdf", height=10, width=15)
dev.off


# now by lake for rarefied 500
test_nmds11.500 <- ggplot(nmds.merge2[(nmds.merge2$time_point == "1"), ], aes(x=NMDS1, y=NMDS2, color = lake)) +
  geom_point(aes(color = lake, shape = phy_group), size = 3) + 
  stat_ellipse(level=0.9, linetype = 2, aes(color = lake)) +
  ggtitle("Time 1") +
  theme_bw()
test_nmds11.500
dev.print(pdf, "phyloseq analysis/figures/test_nmds11.500.pdf", height=10, width=15)
dev.off

test_nmds12.500 <- ggplot(nmds.merge2[(nmds.merge2$time_point == "2"), ], aes(x=NMDS1, y=NMDS2, color = lake)) +
   geom_point(aes(color = lake, shape = phy_group), size = 3) + 
   stat_ellipse(level=0.9, linetype = 2, aes(color = lake)) +
   ggtitle("Time 2") +
   theme_bw()
test_nmds12.500
dev.print(pdf, "phyloseq analysis/figures/test_nmds12.500.pdf", height=10, width=15)
dev.off

test_nmds13.500 <- ggplot(nmds.merge2[(nmds.merge2$time_point == "3"), ], aes(x=NMDS1, y=NMDS2, color = lake)) +
  geom_point(aes(color = lake, shape = phy_group), size = 3) + 
  stat_ellipse(level=0.9, linetype = 2, aes(color = lake)) +
  ggtitle("Time 3") +
  theme_bw()
test_nmds13.500
dev.print(pdf, "phyloseq analysis/figures/test_nmds13.500.pdf", height=10, width=15)
dev.off

test_nmds14.500 <- ggplot(nmds.merge2[(nmds.merge2$time_point == "4"), ], aes(x=NMDS1, y=NMDS2, color = lake)) +
   geom_point(aes(color = lake, shape = phy_group), size = 3) + 
   stat_ellipse(level=0.9, linetype = 2, aes(color = lake)) +
   ggtitle("Time 4") +
   theme_bw()
test_nmds14.500
dev.print(pdf, "phyloseq analysis/figures/test_nmds14.500.pdf", height=10, width=15)
dev.off

test_nmds15.500 <- ggplot(nmds.merge2[(nmds.merge2$time_point == "5"), ], aes(x=NMDS1, y=NMDS2, color = lake)) +
   geom_point(aes(color = lake, shape = phy_group), size = 3) + 
   stat_ellipse(level=0.9, linetype = 2, aes(color = lake)) +
   ggtitle("Time 5") +
   theme_bw()
test_nmds15.500
dev.print(pdf, "phyloseq analysis/figures/test_nmds15.500.pdf", height=10, width=15)
dev.off

library("patchwork")
library("ggpubr")
library(cowplot)
combined.nmds.lake.500 <- ggarrange(test_nmds11.500 + theme(axis.title.y=element_text(size=8)),
          test_nmds12.500 + theme(axis.title.y=element_text(size=8)),
          test_nmds13.500 + theme(axis.title.y=element_text(size=8)),
          test_nmds14.500 + theme(axis.title.y=element_text(size=8)),
          test_nmds15.500 + theme(axis.title.y=element_text(size=8)),
          plot_layout(guides="collect"), labels=NULL, common.legend = TRUE, 
          legend="bottom", align="hv", 
          font.label = list(size=10, color="black", family=NULL, position="top", labels="auto"))
combined.nmds.lake.500
dev.print(pdf, "phyloseq analysis/figures/combined.nmds.lake.500.pdf", height=10, width=15)
dev.off





library("patchwork")
library("ggpubr")
library(cowplot)





```
```{r NMDS using bc- lake, time_point, phy_group}
centroid <- nmds2.merge %>% 
  group_by(lake) %>%
  summarize(NMDS1 = mean(NMDS1), NMDS2 = mean(NMDS2))

time.ord <- ordinate(PS.zoops, method = 'PCoA', distance = "bray")
time.MDS <- plot_ordination(PS.zoops, time.ord) +
  geom_point(aes(color = time_point), size = 3) +
  stat_ellipse(level=0.9, linetype = 2, aes(color=time_point)) +
  scale_color_brewer(palette = "Dark2") +
  scale_fill_brewer(palette = "Dark2") +
  theme_classic()
time.MDS

nmds.type.lake.time <- ggplot(nmds.merge3, aes(x=NMDS1, y=NMDS2, color = time_point)) +
  geom_point(aes(color = time_point), size = 3) + 
  stat_ellipse(level=0.9, linetype = 2, aes(color=time_point)) +
  theme_bw()

nmds.time <- ggplot(nmds.merge2, aes(x=NMDS1, y=NMDS2, color = time_point)) +
  geom_point(aes(color = time_point), size = 3) + 
  stat_ellipse(level=0.9, linetype = 2, aes(color=time_point)) +
  theme_bw()
nmds.time
dev.print(pdf, "phyloseq analysis/figures/nmds.time.pdf", height=10, width=15)
dev.off

nmds.lake <- ggplot(nmds.merge3, aes(x=NMDS1, y=NMDS2, color = lake)) +
  geom_point(aes(color = lake), size = 3) + 
  stat_ellipse(level=0.9, linetype = 2, aes(color=lake)) +
  theme_bw()
nmds.lake
dev.print(pdf, "phyloseq analysis/figures/nmds.lake.pdf", height=10, width=15)
dev.off

nmds.basin <- ggplot(nmds.merge2, aes(x=NMDS1, y=NMDS2, color = basin)) +
  geom_point(aes(color = basin), size = 3) + 
  stat_ellipse(level=0.9, linetype = 2, aes(color=basin)) +
  theme_bw()
nmds.basin
dev.print(pdf, "phyloseq analysis/figures/nmds.basin.pdf", height=10, width=15)
dev.off

nmds.elevation <- ggplot(nmds.merge2, aes(x=NMDS1, y=NMDS2, color = elev.cat)) +
  geom_point(aes(color = elev.cat), size = 3) + 
  stat_ellipse(level=0.9, linetype = 2, aes(color=elev.cat)) +
  theme_bw()
nmds.elevation
dev.print(pdf, "phyloseq analysis/figures/nmds.elevation.pdf", height=10, width=15)
dev.off
  
nmds.sample_type <- ggplot(nmds.merge2, aes(x=NMDS1, y=NMDS2, color = sample_type)) +
  geom_point(aes(color = sample_type), size = 3) + 
  stat_ellipse(level=0.9, linetype = 2, aes(color=sample_type)) +
  theme_bw()
nmds.sample_type
dev.print(pdf, "phyloseq analysis/figures/nmds.sample_type.pdf", height=10, width=15)
dev.off

nmds.phy_group <- ggplot(nmds.merge2, aes(x=NMDS1, y=NMDS2, color = phy_group)) +
  geom_point(aes(color = phy_group), size = 3) + 
  stat_ellipse(level=0.9, linetype = 2, aes(color=phy_group)) +
  theme_bw()
nmds.phy_group
dev.print(pdf, "phyloseq analysis/figures/nmds.phy_group.pdf", height=10, width=15)
dev.off


```





```{r dbRDA}


dbRDA <- dbrda(bc_500 ~ longitude + latitude + DO_perc + chla_ug.L + 
                  cond + lake, data = nmds.merge2)
anova(dbRDA, by="terms", permu = 200)
summary(dbRDA)
plot(dbRDA)
mod_selec <- ordiR2step(dbRDA, scope = formula(upr))

```


```{r PCA}
all_pca <- ordinate(
  physeq = PS.500, 
  method = "PCA", 
  distance = "bray"
)

PCA.ord.plot <- plot_ordination(
  physeq = PS.500,                                                       
  ordination = all_pca, color = "time_point") +                                                
  geom_point(aes(color = phy_group), size = 3) +  
  stat_ellipse(type = "norm", linetype = 2, aes(color=time_point)) +
  scale_shape_manual(values = c(21, 22, 23, 24, 25)) +
  theme_classic() +                                                      
  theme(                             
    legend.text = element_text(size = 12),                               
    legend.title = element_blank(),                                      
    legend.background = element_rect(fill = "white", color = "NA"))+  
  theme(axis.text.y.left = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12))+
  guides(fill = guide_legend(override.aes = list(shape = 21))) 

PCoA.ord.plot
dev.copy(pdf, "phyloseq analysis/figures/PCoA.pdf", height=7, width=10)
dev.off() 

```
```{r stacked bar phylum - incorrect}

# make colors for sites
library(RColorBrewer)
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

# merge all to phylum level

ps.rare_phylum <- physeq.rare500 %>%
  tax_glom(taxrank = "Phylum") %>%                     # agglomerate at phylum level
  transform_sample_counts(function(x) {x/sum(x)} ) %>% # Transform to rel. abundance
  psmelt() %>%                                         # Melt to long format
  filter(Abundance > 0.02) %>%                         # Filter out low abundance taxa
  arrange(Phylum) 

phylum_colors<-col_vector

# Plot 
Bac.Phyla.stacked.bar<-
  ggplot(ps.rare_phylum, aes(x = phy_group, y = Abundance, fill = Phylum)) + 
  #facet_grid(site~.) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = phylum_colors) +
  guides(fill = guide_legend(reverse = TRUE, keywidth = 1, keyheight = 1)) +
  ylab("Relative Abundance (Phyla > 2%) \n") +
  xlab("Site")+
  ggtitle("Phylum Composition of Bacterial Communities by Site") +
  theme(axis.text.x=element_text(angle = 30))


Bac.Phyla.stacked.bar
ggsave(filename = "figures/Bac.Phyla.stacked.bar.pdf", plot = Bac.Phyla.stacked.bar, height=5.5, width=10)
dev.copy(pdf, "figures/Bac.Phyla.stacked.bar.pdf", height=5.5, width=10)
dev.off() 





ps.rare_phylum1 <- ps.rare %>%
  tax_glom(taxrank = "Phylum") %>%                     # agglomerate at phylum level
  transform_sample_counts(function(x) {x/sum(x)} ) %>% # Transform to rel. abundance
  psmelt() %>%                                         # Melt to long format
  arrange(Phylum) 


Bac.Phyla.stacked.bar1<-
  ggplot(ps.rare_phylum1, aes(x = location, y = Abundance, fill = Phylum)) +
  #facet_grid(site~.) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = phylum_colors) +
  guides(fill = guide_legend(reverse = TRUE, keywidth = 1, keyheight = 1)) +
  ylab("Relative Abundance") +
  xlab("Site")+
  ggtitle("Phylum Composition of Bacterial Communities by Site") +
  theme(axis.text.x=element_text(angle = 30))


Bac.Phyla.stacked.bar1
ggsave(filename = "figures/Bac.Phyla.stacked.bar1.pdf", plot = Bac.Phyla.stacked.bar1, height=5.5, width=10)
```




```{r stacked bar Phylum - correct?}


# testing something out from online

ps_rel_abund = phyloseq::transform_sample_counts(PS.fin, function(x){x / sum(x)})
phyloseq::plot_bar(ps_rel_abund, fill = "Class") +
  geom_bar(aes(color = Class, fill = Class), stat = "identity", position = "stack") +
  labs(x = "", y = "Relative Abundance/n") +
  theme(panel.background = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

ps_phylum <- phyloseq::tax_glom(PS.2300, "Class")
phyloseq::taxa_names(ps_phylum) <- phyloseq::tax_table(ps_phylum)[, "Class"]
phyloseq::psmelt(ps_phylum) %>%
ggplot(data = ., aes(x = Status, y = Abundance)) +
  geom_boxplot(outlier.shape  = NA) +
  geom_jitter(aes(color = OTU), height = 0, width = .2) +
  labs(x = "", y = "Abundance\n") +
  facet_wrap(~ OTU, scales = "free")

plot_bar(PS.fin, "time_point", "Abundance", fill = "Phylum") + 
  geom_bar(aes(color = Phylum, fill = Phylum), stat = "identity", position = "stack")

PS.merge <- merge_samples(PS.fin, "time_point")
sample_data(PS.merge)$time_point = factor(sample_names(PS.merge))


# testing out method from Chris
rm(ASV_dataframe)
ASV_rel_abund <- transform_sample_counts(PS.fin, function(x) x/sum(x))
ASV_dataframe <- psmelt(ASV_rel_abund)
ASV_dataframe$Adj.Abundance <- ifelse(ASV_dataframe$Abundance < 1e-2, 0, ASV_dataframe$Abundance)
Abund <- aggregate(Adj.Abundance ~ sequence_ID + time_point + lake + organism_water + phy_group + 
                     Phylum + Class + Order + Family +
                     Genus + Species, data=ASV_dataframe, FUN=mean)

ASV_rel_abund500 <- transform_sample_counts(PS.500, function(x) x/sum(x))
ASV_dataframe500 <- psmelt(ASV_rel_abund500)
#ASV_dataframe500$Abundance <- ifelse(ASV_dataframe500$Abundance < 2e-2, 0, ASV_dataframe500$Abundance)
Abund500 <- aggregate(Abundance ~ sequence_ID + time_point + lake + organism_water + phy_group + sample_type +
                     Phylum + Class + Order + Family +
                     Genus+Species, data=ASV_dataframe500, FUN=mean)

ASV_rel_abund_zoops <- transform_sample_counts(PS.zoops, function(x) x/sum(x))
ASV_dataframe_zoops <- psmelt(ASV_rel_abund_zoops)
#ASV_dataframe1000$Abundance <- ifelse(ASV_dataframe_zoops$Abundance < 1e-2, 0, ASV_dataframe_zoops$Abundance)
Abund_zoops <- aggregate(Abundance ~ sequence_ID + time_point + lake + organism_water + phy_group + 
                     Phylum + Class + Order + Family +
                     Genus+Species, data=ASV_dataframe_zoops, FUN=mean)


ASV_rel_abund_water <- transform_sample_counts(PS.water, function(x) x/sum(x))
ASV_dataframe_water <- psmelt(ASV_rel_abund_water)
#ASV_dataframe1000$Abundance <- ifelse(ASV_dataframe_zoops$Abundance < 1e-2, 0, ASV_dataframe_zoops$Abundance)
Abund_water <- aggregate(Abundance ~ time_point + lake + organism_water + 
                     Phylum + Class + Order + Family +
                     Genus+Species, data=ASV_dataframe_water, FUN=mean)


# testing to see if all the relative abundances of each ASV within sample 1 add up to 1
length(which(ASV_dataframe500$Sample == "322_16S"))
sample322 <- ASV_dataframe500$Sample == "322_16S"
test <- as.matrix(ASV_dataframe500[sample322, "Abundance"])
sum(test)

Abund.fa <- Abund[(Abund$Family=="Burkholderiales"),]
p1 <- ggplot(Abund, aes(x = time_point, y = Abundance, fill= Family)) +
  geom_bar(aes(fill = Family), stat ="identity", position ="fill") +
  facet_grid(cols=vars(phy_group), rows=vars(lake))

phy_group_gen <- ggplot(Abund500, aes(x = phy_group, y = Abundance, fill= Class, color = Class)) +
  geom_bar(aes(fill = Class), stat ="identity", position ="fill") +
  xlab("Sampling Time Point") +
  theme_bw() + theme(axis.text.x=element_text(size=17)) +
  theme(axis.text.y=element_text(size=10)) +
  theme(strip.text.y = element_text(size = 15)) +
  scale_fill_manual(values = c("red4", "orangered", "gold", "lightgreen", "turquoise3", "seagreen4", "lightskyblue", "navy", "skyblue4", "royalblue3", "purple3", "tan3", "black", "antiquewhite2")) +
  scale_color_manual(values = c("red4", "orangered", "gold", "lightgreen", "turquoise3", "seagreen4", "lightskyblue", "navy", "skyblue4", "royalblue3", "purple3", "tan3", "black", "antiquewhite2"))
phy_group_gen
dev.copy(pdf, "phyloseq analysis/figures/phy_group_gen.pdf", height=8, width=7)
dev.off()

phy_group_gen <- ggplot(Abund500, aes(x = phy_group, y = Abundance, fill= Genus, color = Genus)) +
  geom_bar(aes(fill = Genus), stat ="identity", position ="fill") +
  xlab("Sampling Time Point") +
  theme_bw() + theme(axis.text.x=element_text(size=17)) +
  theme(axis.text.y=element_text(size=10)) +
  theme(strip.text.y = element_text(size = 15)) 
phy_group_gen
dev.copy(pdf, "phyloseq analysis/figures/phy_group_gen.pdf", height=8, width=7)
dev.off()

Facet <- ggplot(Abund, aes(x = time_point, y = Abundance, fill= Class)) +
  geom_bar(aes(fill = Class), stat ="identity", position ="fill") +
  facet_grid(cols=vars(phy_group), rows=vars(lake)) + xlab("Sampling Time Point")
Facet
dev.copy(pdf, "phyloseq analysis/figures/Facet.pdf", height=7, width=10)
dev.off()

Facet500 <- ggplot(Abund500, aes(x = time_point, y = Abundance, fill= Class, color = Class)) +
  geom_bar(aes(fill = Class), stat ="identity", position = "fill") +
  facet_grid(rows = vars(phy_group), cols = vars(lake)) + xlab("Sampling Time Point") +
  theme_bw() + theme(axis.text.x=element_text(size=17)) +
  theme(axis.text.y=element_text(size=10)) +
  theme(strip.text.y = element_text(size = 15)) +
  scale_fill_manual(values = c("red4", "orangered", "gold", "lightgreen", "turquoise3", "seagreen4", "lightskyblue", "navy", "skyblue4", "royalblue3", "tan3", "purple3", "black", "antiquewhite2")) +
  scale_color_manual(values = c("red4", "orangered", "gold", "lightgreen", "turquoise3", "seagreen4", "lightskyblue", "navy", "skyblue4", "royalblue3", "tan3", "purple3", "black", "antiquewhite2"))
Facet500
dev.copy(pdf, "phyloseq analysis/figures/Facet500.pdf", height=6, width=8)
dev.off()

Facet_sampletype <- ggplot(Abund500, aes(x = time_point, y = Abundance, fill= Class)) +
  geom_bar(aes(fill = Class), stat ="identity", position ="fill") +
  facet_grid(cols = vars(sample_type)) + xlab("Sampling Time Point") +
  theme_bw() + theme(axis.text.x=element_text(size=17)) +
  theme(strip.text.y = element_text(size = 20)) +
  theme(axis.text.y=element_text(size=10)) +
  theme(strip.text.y = element_text(size = 10)) +
  scale_fill_manual(values = c("red4", "orangered", "gold", "lightgreen", "turquoise3", "seagreen4", "lightskyblue", "navy", "skyblue4", "royalblue3", "tan3", "purple3", "black", "antiquewhite2"))
Facet_sampletype
dev.copy(pdf, "phyloseq analysis/figures/Facet_sampletype.pdf", height=7, width=10)
dev.off()

Facet500_genus <- ggplot(Abund500, aes(x = time_point, y = Abundance, fill= Genus)) +
  geom_bar(aes(fill = Genus), stat ="identity", position ="fill") +
  xlab("Sampling Time Point") + theme_bw()
Facet500_genus
dev.copy(pdf, "phyloseq analysis/figures/Facet500_order.pdf", height=10, width=5)
dev.off()


Facet_zoops <- ggplot(Abund_zoops, aes(x = time_point, y = Abundance, fill= Class, color = Class)) +
  geom_bar(aes(fill = Class), stat ="identity", position ="fill") +
  facet_grid(rows=vars(phy_group), cols = vars(lake)) + xlab("Sampling Time Point") +
  scale_fill_manual(values = c("red4", "orangered", "gold", "lightgreen", "turquoise3", "seagreen4", "lightskyblue", "navy", "skyblue4", "purple3", "royalblue3", "tan3", "black", "antiquewhite2")) +
  scale_color_manual(values = c("red4", "orangered", "gold", "lightgreen", "turquoise3", "seagreen4", "lightskyblue", "navy", "skyblue4", "purple3", "royalblue3", "tan3", "black", "antiquewhite2"))
Facet_zoops
dev.copy(pdf, "phyloseq analysis/figures/Facet_zoops.pdf", height=5, width=10)
dev.off()

Facet_zoops_general <- ggplot(Abund_zoops, aes(x = time_point, y = Abundance, fill= Class, color = Class)) +
  geom_bar(aes(fill = Class), stat ="identity", position ="fill") +
  xlab("Sampling Time Point") +
  scale_fill_manual(values = c("red4", "orangered", "gold", "lightgreen", "turquoise3", "seagreen4", "lightskyblue", "navy", "skyblue4", "purple3", "royalblue3", "tan3", "black", "antiquewhite2")) +
  scale_color_manual(values = c("red4", "orangered", "gold", "lightgreen", "turquoise3", "seagreen4", "lightskyblue", "navy", "skyblue4", "purple3", "royalblue3", "tan3", "black", "antiquewhite2")) +
  ggtitle("Zooplankton microbiome compositions")
Facet_zoops_general
dev.copy(pdf, "phyloseq analysis/figures/Facet_zoops_general.pdf", height=7, width=10)
dev.off()


# by lake and time_point
stacked1 <- ggplot(data=Abund_zoops, aes(x = time_point, y = Abundance), fill = Class) +
  geom_bar(aes(fill = Class), stat ="identity", position ="fill") +
  scale_fill_manual(values = c("red4", "orangered", "gold", "lightgreen", "turquoise3", "seagreen4", "lightskyblue", "navy", "skyblue4", "purple3", "royalblue3", "tan3", "black", "antiquewhite2")) +
  facet_grid(col=vars(lake), row=vars(phy_group), scales="free") + theme(axis.text.x=element_text(size=20)) +
  theme(strip.text.x = element_text(size = 15)) + xlab("Sampling Time Point") + theme_bw() + ggtitle("Zooplankton microbiome compositions")
stacked1
dev.copy(pdf, "phyloseq analysis/figures/stacked1.pdf", height=7, width=12)
dev.off() 

# facet_grid(col=vars(time_point), scales="free")
stacked.phy_group <- ggplot(data=Abund, aes(x = phy_group, y = Abundance), fill = Class) +
  geom_bar(aes(fill = Class), stat ="identity", position ="fill", width = 0.75) +
  scale_fill_manual(values = c("red4", "orangered", "gold", "lightgreen", "turquoise3", "olivedrab3", "seagreen4", "lightskyblue", "navy", "skyblue4", "purple3", "royalblue3", "violetred", "tan3", "darkorange4", "grey60", "black", "antiquewhite2")) + 
  xlab("Sample Type") + theme(axis.text.x=element_text(size=20)) + theme(strip.text.x = element_text(size = 20)) + theme_bw() + ggtitle("Unrarefied")
stacked.phy_group
dev.copy(pdf, "phyloseq analysis/figures/stacked.phy_group.pdf", height=7, width=12)
dev.off() 
###

water.only <- ggplot(Abund_water, aes(x = organism_water, y = Abundance, fill = Class, color = Class)) +
  geom_bar(aes(fill = Class), width = 0.2, stat ="identity", position ="fill") +
  scale_fill_manual(values = c("red4", "orangered", "gold", "lightgreen", "turquoise3", "olivedrab3", "seagreen4", "lightskyblue", "navy", "skyblue4", "purple3", "royalblue3", "violetred", "tan3", "darkorange4", "grey60", "black", "antiquewhite2")) +
  scale_color_manual(values = c("red4", "orangered", "gold", "lightgreen", "turquoise3", "olivedrab3", "seagreen4", "lightskyblue", "navy", "skyblue4", "purple3", "royalblue3", "violetred", "tan3", "darkorange4", "grey60", "black", "antiquewhite2")) +
  xlab("Sampling Time Point") + theme(axis.text.x=element_text(size=20)) + theme(strip.text.x = element_text(size = 20)) + theme_bw() + ggtitle("Free-living microbial communities")
water.only
dev.copy(pdf, "phyloseq analysis/figures/water.only.pdf", height=7, width=12)
dev.off() 

library("patchwork")
library("ggpubr")


combined.stacked.plot <- ggarrange(Facet_zoops_general + theme(axis.title.y=element_text(size=8)),
                           water.only + theme(axis.title.y=element_text(size=8)),
                           labels = c("A", "B"),
                           common.legend = TRUE, legend="bottom",
                           align="hv", font.label = list(size=10, color="black", family=NULL, position = "top"))
combined.stacked.plot
dev.print(pdf, "phyloseq analysis/figures/combined.stacked.plot.pdf")
dev.off

zoops.v.water <- ggplot(Abund500, aes(x = sample_type, y = Abundance), fill = Class) +
  geom_bar(aes(fill = Class), stat ="identity", position ="fill") +
  facet_grid(col=vars(sample_type), scales="free") +
  scale_fill_manual(values = c("red4", "orangered", "gold", "lightgreen", "turquoise3", "seagreen4", "lightskyblue", "navy", "skyblue4", "royalblue3", "tan3", "purple3", "black", "antiquewhite2")) +
  xlab("Sampling Time Point") + theme(axis.text.x=element_text(size=20)) + theme(strip.text.x = element_text(size = 20)) + theme_bw() + ggtitle("Cladocera and Copepoda Microbiomes vs. free-living microbial communities")
zoops.v.water
dev.copy(pdf, "phyloseq analysis/figures/zoops.v.water.pdf", height=7, width=12)
dev.off() 

# time point 1
stacked2 <- ggplot(data=Abund[Abund$time_point=="1",], aes(x = lake, y = Abundance), fill = Phylum) +
  geom_bar(aes(color = Phylum, fill = Phylum, ), stat ="identity", position ="fill") +
  theme(legend.position="bottom") + guides(fill=guide_legend(nrow=7)) + 
  facet_grid(~time_point, scales="free") + theme(axis.text.x = element_text(angle = 90))
stacked2
dev.copy(pdf, "phyloseq analysis/figures/stacked2.pdf", height=7, width=10)
dev.off() 

# by time_point for Blue
stacked3 <- ggplot(data=Abund[Abund$lake =="Blue",], aes(x = lake, y = Abundance), fill = Phylum) +
  geom_bar(aes(color = Phylum, fill = Phylum, ), stat ="identity", position ="fill") +
  facet_grid(~time_point, scales="free")
stacked3
dev.copy(pdf, "phyloseq analysis/figures/stacked3.pdf", height=7, width=10)
dev.off() 

# by time_point for Eastern Brook
stacked <- ggplot(data=Abund[Abund$lake =="Eastern Brook",], aes(x = lake, y = Abundance), fill = Phylum) +
  geom_bar(aes(color = Phylum, fill = Phylum, ), stat ="identity", position ="fill") +
  facet_grid(~time_point, scales="free")
stacked
dev.copy(pdf, "phyloseq analysis/figures/stacked.pdf", height=7, width=10)
dev.off() 

# time_point by phy_group
stacked4 <- ggplot(data=Abund[Abund$time_point=="1",], aes(x = phy_group, y = Abundance), fill = Class) +
  geom_bar(aes(color = Class, fill = Class, ), stat ="identity", position ="fill") +
  facet_grid(~time_point, scales="free") + theme(axis.text.x = element_text(angle = 90))

stacked4
dev.copy(pdf, "phyloseq analysis/figures/stacked4.pdf", height=7, width=10)
dev.off() 

stacked5 <- ggplot(data=Abund[Abund$time_point=="2",], aes(x = phy_group, y = Abundance), fill = Class) +
  geom_bar(aes(color = Class, fill = Class, ), stat ="identity", position ="fill") +
  facet_grid(~time_point, scales="free") + theme(axis.text.x = element_text(angle = 90))

stacked5
dev.copy(pdf, "phyloseq analysis/figures/stacked5.pdf", height=7, width=10)
dev.off() 

stacked6 <- ggplot(data=Abund[Abund$time_point=="3",], aes(x = phy_group, y = Abundance), fill = Class) +
  geom_bar(aes(color = Class, fill = Class, ), stat ="identity", position ="fill") +
  facet_grid(~time_point, scales="free") + theme(axis.text.x = element_text(angle = 90))

stacked6
dev.copy(pdf, "phyloseq analysis/figures/stacked6.pdf", height=7, width=10)
dev.off() 

stacked7 <- ggplot(data=Abund[Abund$time_point=="4",], aes(x = phy_group, y = Abundance), fill = Class) +
  geom_bar(aes(color = Class, fill = Class, ), stat ="identity", position ="fill") +
  facet_grid(~time_point, scales="free") + theme(axis.text.x = element_text(angle = 90))

stacked7
dev.copy(pdf, "phyloseq analysis/figures/stacked7.pdf", height=7, width=10)
dev.off() 


stacked8 <- ggplot(data=Abund[Abund$time_point=="5",], aes(x = phy_group, y = Abundance), fill = Class) +
  geom_bar(aes(color = Class, fill = Class, ), stat ="identity", position ="fill") +
  facet_grid(~time_point, scales="free") + theme(axis.text.x = element_text(angle = 90))

stacked8
dev.copy(pdf, "phyloseq analysis/figures/stacked8.pdf", height=7, width=10)
dev.off()



```

```{r Jon's help with bar plots}
ASV_abund <- transform_sample_counts(PS.fin,function(x) x)
ASV_reads_DF <- psmelt(ASV_abund)

Reads<-aggregate(Abundance~time_point+lake+organism_water+phy_group+elevation_m+
                   temp_C+Phylum+Class+Order+Family+Genus+Species, data=ESV_reads_DF, FUN=sum)
#Reads<-aggregate(Abundance~time_point+lake+organism_water+phy_group+elevation_m+temp_C+Phylum, data=ESV_reads_DF, FUN=sum)

Reads$samp_tot<-summaryBy(Abundance~time_point + lake + organsim_water + phy_group, 
                          data=Reads, FUN="sum")

library(doBy)
x<-summaryBy(Abundance~lake+time_point, data=Abund, FUN="mean")
```



```{r Using physeq.rare to make community comp figure }



# aggregating ASVs by class 
class_counts_tab <- otu_table(tax_glom(PS.fin, taxrank="Class"))
class_tax_vec <- as.vector(tax_table(tax_glom(PS.fin, taxrank="Class"))[,"Class"]) 
rownames(class_counts_tab) <- as.vector(class_tax_vec)

# below is aggregating ASVs by phylum 
phyla_counts_tab <- otu_table(tax_glom(PS.fin, taxrank="Phylum")) 
# making rownames phyla 
phyla_tax_vec <- as.vector(tax_table(tax_glom(PS.fin, taxrank="Phylum"))[,"Phylum"]) 
rownames(phyla_counts_tab) <- as.vector(phyla_tax_vec)

# now we have a dataframe with the number of reads corresponding for each phylum and class in each sample 

# making a relative abundance df at the phylum level 
phylum_proportions <- apply(phyla_counts_tab, 2, function(x) x/sum(x))

phylum_proportions <- as.data.frame(phylum_proportions) # making df
phylum_proportions$Phyla <- row.names(phylum_proportions) # column of phyla
# check they all add up to 1
sum(phylum_proportions[,1])





# making data long - sample column, phyla column, relative abundance column 
phylum_prop_long <- phylum_proportions %>% 
  pivot_longer(cols = colnames(phylum_proportions[,1:320]), 
                                    names_to = "sequence_ID", 
                                    values_to = "rel_abund")
phylum_prop_long <- as.data.frame(phylum_prop_long)
str(phylum_prop_long)

# now we have long df with each sample and the rel abundance of phyla 
```




```{r plotting Phylum composition }
# basic figure of mean relative abundance for above and below treeline
phyla_comp %>% 
  group_by(time_point, Phyla) %>% 
  summarize(mean_rel_abund = 100*mean(rel_abund)) %>% 
  ggplot(aes(x=time_point, y=mean_rel_abund, fill=Phyla)) + 
  geom_col() + 
  theme_classic() + 
  scale_fill_discrete(name = NULL) + 
  labs(y = "Mean Relative Abundance (%)", x=NULL) + 
  theme(legend.text = element_text(face = "italic"), 
        legend.key.size = unit(10, "pt"))
ggsave("figures/mean_phyla_bar_raw.tiff", width = 5, height = 4)

# we have the basic figure - now we need to make it more appealing 

# making an "other" category and improving figure based on Pat Schloss suggestion

# seeing maximum mean relative abundance of each phyla in above/below groups 
phyla_mean_rel_abund <- phyla_comp %>% 
  group_by(time_point, Phyla) %>% 
  summarize(mean_rel_abund = 100*mean(rel_abund))

max.phyla <- phyla_mean_rel_abund %>% 
  group_by(Phyla) %>% 
  summarize(max(mean_rel_abund)) 
max.phyla <- max.phyla[order(max.phyla$'max(mean_rel_abund)'), decreasing = FALSE]

# we can see our most abundant phyla: Firmicutes, Fusobacteriota, Proteobacteria, Cyanobacteria, Actinobacteriota (maybe)

# pooling everything over 5% using a logical 
phyla_pool <- phyla_mean_rel_abund %>% 
  group_by(Phyla) %>% 
  summarize(pool = max(mean_rel_abund) < 5, 
            mean = mean(mean_rel_abund)) # this creates a logical of if a phyla meets the condition (is less than 5%)

# join with df and plot! 
inner_join(phyla_mean_rel_abund, phyla_pool, by = "Phyla") %>% 
  mutate(Phyla = if_else(pool, "Other", Phyla)) %>%
  group_by(time_point, Phyla) %>% 
  summarize(mean_rel_abund = sum(mean_rel_abund),
            mean = sum(mean)) %>% 
  mutate(Phyla = factor(Phyla), 
         Phyla = fct_reorder(Phyla, mean, .desc = TRUE), 
         Phyla = fct_shift(Phyla, n=1)) %>%
  ggplot(aes(x=time_point, y=mean_rel_abund, fill=Phyla)) + 
  geom_col() + 
  theme_classic() + 
  scale_fill_manual(name = NULL, 
                    breaks = c("Cyanobacteria", "Firmicutes", "Fusobacteriota", 
                               "Proteobacteria", "Other"), 
                    values = c(brewer.pal(4, "Set1"), "gray")) +
  labs(y = "Mean Relative Abundance (%)", x=NULL) + 
  theme(legend.text = element_text(face = "italic"), 
        legend.key.size = unit(12, "pt"))
ggsave("figures/phyla_comp_condensed.tiff", height = 4, width = 5)
```

